import type { EconomyMaterialCost, ItemCategory } from './types'
import type { MarketCategory } from './market-catalog'

/** Sottocategoria mercato — armi, protezioni, veicoli, consumabili craft. */
export type MarketEquipmentKind =
  | 'arma_bianca'
  | 'arma_fuoco'
  | 'arma_lancio'
  | 'protezione'
  | 'veicolo'
  | 'consumabile'

export type MarketEquipmentLegacyType = 'WEAPON' | 'ARMOR' | 'GENERIC'

const KIND_TO_MARKET_CATEGORY: Record<MarketEquipmentKind, MarketCategory> = {
  arma_bianca: 'armi',
  arma_fuoco: 'armi',
  arma_lancio: 'armi',
  protezione: 'armature',
  veicolo: 'veicoli',
  consumabile: 'rimedi',
}

export interface MarketEquipmentDef {
  /** Chiave catalogo stabile (es. `equip-sabimaru`). */
  readonly id: string
  readonly kind: MarketEquipmentKind
  readonly category: ItemCategory
  readonly type: MarketEquipmentLegacyType
  /** Romaji (Kanji), es. "Sabimaru (錆丸)". */
  readonly nameRomaji: string
  /** Titolo italiano, es. "La Lama Arrugginita". */
  readonly nameItalian: string
  readonly description: string
  readonly integrityMax?: number
  /** Regole meccaniche brevi (scheda oggetto). */
  readonly effectText: string
  readonly inventorySlotCost: number
  readonly isStackable: boolean
  readonly blueprintId?: string
  readonly craftMaterials?: readonly EconomyMaterialCost[]
  /** Prezzo Rem nel catalogo Market — provvisorio, tarabile da Sviluppo. */
  readonly priceRem: number
}

/** Categoria Market (vetrina a card) derivata dalla sottocategoria meccanica. */
export function marketEquipmentCategory(kind: MarketEquipmentKind): MarketCategory {
  return KIND_TO_MARKET_CATEGORY[kind]
}

/** Catalogo equipaggiamento mercato — 20 armi, 10 protezioni, 5 veicoli (+ Kaen-bin consumabile). */
export const MARKET_EQUIPMENT_CATALOG: readonly MarketEquipmentDef[] = [
  // ─── Armi bianche (8) ───
  {
    id: 'equip-sabimaru',
    kind: 'arma_bianca',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Sabimaru (錆丸)',
    nameItalian: 'La Lama Arrugginita',
    description:
      'Katana del vecchio mondo, mangiata dalla ruggine ma ancora letale. L\'arma più comune tra chi combatte.',
    integrityMax: 20,
    effectText: 'Arma da mischia',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 60,
  },
  {
    id: 'equip-kubikiri',
    kind: 'arma_bianca',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Kubikiri (首切り)',
    nameItalian: 'Il Taglia-Colli',
    description:
      'Mannaia massiccia da macello, riforgiata per la guerra. Lenta, brutale, pesantissima.',
    integrityMax: 30,
    effectText: 'Arma da mischia · richiede Kairiki 3+',
    inventorySlotCost: 2,
    isStackable: false,
    priceRem: 90,
  },
  {
    id: 'equip-hotarubi',
    kind: 'arma_bianca',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Hotarubi (蛍火)',
    nameItalian: 'La Lucciola',
    description:
      'Tantō corto con lama brunita che non riflette la luce. L\'arma del lavoro silenzioso.',
    integrityMax: 15,
    effectText: 'Arma da mischia · +1 Indice nelle azioni furtive',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 45,
  },
  {
    id: 'equip-onikama',
    kind: 'arma_bianca',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Onikama (鬼鎌)',
    nameItalian: 'La Falce dell\'Orco',
    description: 'Kusarigama: falce con catena zavorrata.',
    integrityMax: 20,
    effectText: 'Portata 3 m · può agganciare arti o armi',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 60,
  },
  {
    id: 'equip-yarinobori',
    kind: 'arma_bianca',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Yarinobori (槍昇り)',
    nameItalian: 'La Lancia Ascendente',
    description: 'Yari da fanteria con asta in metallo recuperato.',
    integrityMax: 25,
    effectText: 'Chi la impugna ingaggia a 2 m',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 75,
  },
  {
    id: 'equip-kanabo-namida',
    kind: 'arma_bianca',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Kanabō no Namida (金棒の涙)',
    nameItalian: 'La Lacrima del Demone',
    description: 'Mazza kanabō tempestata di bulloni e chiodi industriali.',
    integrityMax: 30,
    effectText: 'Ignora 2 Scudo del bersaglio · richiede Kairiki 4+',
    inventorySlotCost: 2,
    isStackable: false,
    priceRem: 90,
  },
  {
    id: 'equip-kagenui-hari',
    kind: 'arma_bianca',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Kagenui no Hari (影縫いの針)',
    nameItalian: 'L\'Ago Cuci-Ombre',
    description: 'Stiletto sottilissimo ricavato da un raggio di bicicletta temprato. Quasi invisibile in mano.',
    integrityMax: 10,
    effectText: 'Non rilevabile nelle perquisizioni sommarie',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 30,
  },
  {
    id: 'equip-nokogiri-to',
    kind: 'arma_bianca',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Nokogiri-tō (鋸刀)',
    nameItalian: 'La Spada-Sega',
    description: 'Lama dentata ricavata da una sega industriale.',
    integrityMax: 20,
    effectText: 'Ferite curate dal medico a costo doppio',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 60,
  },

  // ─── Armi da fuoco (7) ───
  {
    id: 'equip-tanuki-me',
    kind: 'arma_fuoco',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Tanuki no Me (狸の目)',
    nameItalian: 'L\'Occhio del Tanuki',
    description: 'Revolver del vecchio mondo, tamburo da 6, affidabile anche sporco.',
    integrityMax: 20,
    effectText: 'Arma da fuoco · tamburo 6 colpi',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 60,
  },
  {
    id: 'equip-kaminari-tsutsu',
    kind: 'arma_fuoco',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Kaminari-tsutsu (雷筒)',
    nameItalian: 'Il Tubo del Tuono',
    description: 'Fucile a canna liscia artigianale, canna ricavata da tubatura idraulica.',
    integrityMax: 15,
    effectText: 'Devastante entro 10 m · inutile oltre',
    inventorySlotCost: 2,
    isStackable: false,
    priceRem: 45,
  },
  {
    id: 'equip-shinigami-yubi',
    kind: 'arma_fuoco',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Shinigami no Yubi (死神の指)',
    nameItalian: 'Il Dito dello Shinigami',
    description: 'Fucile a otturatore con ottica di fortuna. Un colpo, lungo da ricaricare.',
    integrityMax: 20,
    effectText: 'Colpo singolo · ricarica 1 quarto',
    inventorySlotCost: 2,
    isStackable: false,
    priceRem: 60,
  },
  {
    id: 'equip-hachi-su',
    kind: 'arma_fuoco',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Hachi no Su (蜂の巣)',
    nameItalian: 'Il Nido di Vespe',
    description: 'Pistola mitragliatrice recuperata, inceppamenti frequenti.',
    integrityMax: 15,
    effectText: 'Raffica: 2 attacchi/quarto · inceppamento possibile (1 quarto)',
    inventorySlotCost: 2,
    isStackable: false,
    priceRem: 45,
  },
  {
    id: 'equip-karasu-uchi',
    kind: 'arma_fuoco',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Karasu-uchi (烏撃ち)',
    nameItalian: 'Lo Scaccia-Corvi',
    description: 'Doppietta a canne mozze da contadino.',
    integrityMax: 20,
    effectText: 'Due colpi · poi ricarica',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 60,
  },
  {
    id: 'equip-yumihari',
    kind: 'arma_fuoco',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Yumihari (弓張り)',
    nameItalian: 'L\'Arco Teso',
    description: 'Balestra pesante con verricello, silenziosa e riutilizzabile — i dardi si recuperano.',
    integrityMax: 20,
    effectText: 'Balestra · ricarica 1 quarto · dardi recuperabili',
    inventorySlotCost: 2,
    isStackable: false,
    priceRem: 60,
  },
  {
    id: 'equip-hinawa',
    kind: 'arma_fuoco',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Hinawa (火縄)',
    nameItalian: 'La Miccia',
    description: 'Pistola a colpo singolo di fabbricazione artigianale (Kajishi), stile tanegashima.',
    integrityMax: 10,
    effectText: 'Colpo singolo · ricarica 1 quarto · dopo lo sparo la posizione è nota a tutti',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 30,
  },

  // ─── Armi da lancio (4 equip + 1 consumabile) ───
  {
    id: 'equip-tsubute',
    kind: 'arma_lancio',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Tsubute (礫)',
    nameItalian: 'I Sassi del Silenzio',
    description: 'Set di 6 pesi metallici da lancio, riutilizzabili.',
    integrityMax: 10,
    effectText: 'Danno basso · zero rumore · set da 6',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 30,
  },
  {
    id: 'consumable-kaen-bin',
    kind: 'consumabile',
    category: 'consumabile',
    type: 'GENERIC',
    nameRomaji: 'Kaen-bin (火炎瓶)',
    nameItalian: 'La Bottiglia di Fiamma',
    description: 'Molotov artigianale. Consumabile.',
    effectText: 'Area 2 m in fiamme per 2 turni · danno da fuoco a chi attraversa',
    inventorySlotCost: 1,
    isStackable: true,
    blueprintId: 'artigiano-kaen-bin',
    craftMaterials: [
      { materialId: 'reagente', quantity: 1 },
      { materialId: 'stoffa', quantity: 1 },
    ],
    priceRem: 15,
  },
  {
    id: 'equip-kugi-shuriken',
    kind: 'arma_lancio',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Kugi-shuriken (釘手裏剣)',
    nameItalian: 'Le Stelle di Chiodi',
    description: 'Shuriken saldati da chiodi da cantiere.',
    integrityMax: 10,
    effectText: 'Set da 8 · metà recuperabile dopo l\'uso',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 30,
  },
  {
    id: 'equip-doku-fukiya',
    kind: 'arma_lancio',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Doku-fukiya (毒吹き矢)',
    nameItalian: 'La Cerbottana Avvelenata',
    description: 'Cerbottana in canna di bambù + dardi.',
    integrityMax: 10,
    effectText: 'Danno irrisorio · i dardi accettano veleni Yakushi',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 30,
  },
  {
    id: 'equip-kusari-tama',
    kind: 'arma_lancio',
    category: 'equipaggiamento',
    type: 'WEAPON',
    nameRomaji: 'Kusari-tama (鎖玉)',
    nameItalian: 'La Sfera Incatenata',
    description: 'Bolas di catene e pesi.',
    integrityMax: 15,
    effectText: 'Immobilizza le gambe (1 turno o confronto per liberarsi)',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 45,
  },

  // ─── Protezioni (10) ───
  {
    id: 'equip-boro-yoroi',
    kind: 'protezione',
    category: 'equipaggiamento',
    type: 'ARMOR',
    nameRomaji: 'Boro no Yoroi (襤褸の鎧)',
    nameItalian: 'L\'Armatura di Stracci',
    description: 'Strati di stoffa pressata e cucita. La protezione dei disperati.',
    integrityMax: 10,
    effectText: 'Scudo 4 (T1)',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 30,
  },
  {
    id: 'equip-kawa-dogi',
    kind: 'protezione',
    category: 'equipaggiamento',
    type: 'ARMOR',
    nameRomaji: 'Kawa-dōgi (革胴着)',
    nameItalian: 'Il Corpetto di Cuoio',
    description: 'Giubbotto in cuoio trattato, silenzioso e flessibile.',
    integrityMax: 15,
    effectText: 'Scudo 4 (T1) · nessuna penalità',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 45,
  },
  {
    id: 'equip-teppan-do',
    kind: 'protezione',
    category: 'equipaggiamento',
    type: 'ARMOR',
    nameRomaji: 'Teppan-dō (鉄板胴)',
    nameItalian: 'Il Busto di Lamiera',
    description: 'Corazza battuta da segnaletica stradale e lamiere d\'auto.',
    integrityMax: 20,
    effectText: 'Scudo 8 (T2) · −1 m Movimento',
    inventorySlotCost: 2,
    isStackable: false,
    priceRem: 60,
  },
  {
    id: 'equip-taiya-kata',
    kind: 'protezione',
    category: 'equipaggiamento',
    type: 'ARMOR',
    nameRomaji: 'Taiya no Kata (タイヤの肩)',
    nameItalian: 'Le Spalle di Gomma',
    description: 'Spallacci ricavati da pneumatici.',
    integrityMax: 15,
    effectText: 'Scudo 4 (T1) · +2 Scudo extra contro armi da botta',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 45,
  },
  {
    id: 'equip-mushi-karada',
    kind: 'protezione',
    category: 'equipaggiamento',
    type: 'ARMOR',
    nameRomaji: 'Mushi no Karada (蟲の体)',
    nameItalian: 'Il Corpo d\'Insetto',
    description: 'Armatura completa a piastre sovrapposte, sagomata come un carapace.',
    integrityMax: 30,
    effectText: 'Scudo 12 (T3) · −2 m Movimento · richiede Kairiki 3+',
    inventorySlotCost: 3,
    isStackable: false,
    priceRem: 90,
  },
  {
    id: 'equip-mempo-namida',
    kind: 'protezione',
    category: 'equipaggiamento',
    type: 'ARMOR',
    nameRomaji: 'Menpō no Namida (面頬の涙)',
    nameItalian: 'La Maschera che Piange',
    description: 'Mezza maschera in metallo con colature di stagno simili a lacrime.',
    integrityMax: 10,
    effectText: 'Protegge il volto: attacchi mirati alla testa perdono il bonus',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 30,
  },
  {
    id: 'equip-kasa-tate',
    kind: 'protezione',
    category: 'equipaggiamento',
    type: 'ARMOR',
    nameRomaji: 'Kasa no Tate (傘の盾)',
    nameItalian: 'L\'Ombrello-Scudo',
    description: 'Ombrello rinforzato in lamina d\'acciaio, si apre in scudo.',
    integrityMax: 15,
    effectText: 'Scudo 8 (T2) solo se aperto e impugnato',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 45,
  },
  {
    id: 'equip-jizo-sei',
    kind: 'protezione',
    category: 'equipaggiamento',
    type: 'ARMOR',
    nameRomaji: 'Jizō no Sei (地蔵の背)',
    nameItalian: 'La Schiena del Jizō',
    description: 'Scudo dorsale in pietra composita, scolpito come una statuina votiva.',
    integrityMax: 20,
    effectText: 'Scudo 8 (T2) solo dai colpi alle spalle · annulla bonus sorpresa se fugge',
    inventorySlotCost: 2,
    isStackable: false,
    priceRem: 60,
  },
  {
    id: 'equip-kegawa-gaito',
    kind: 'protezione',
    category: 'equipaggiamento',
    type: 'ARMOR',
    nameRomaji: 'Kegawa no Gaitō (毛皮の外套)',
    nameItalian: 'Il Mantello di Pelliccia',
    description: 'Mantello in pelli di preda pregiata (materiale da Kōya no Ryōshi).',
    integrityMax: 15,
    effectText: 'Scudo 4 (T1) · immunità penalità da freddo',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 45,
  },
  {
    id: 'equip-ofuda-kote',
    kind: 'protezione',
    category: 'equipaggiamento',
    type: 'ARMOR',
    nameRomaji: 'Ofuda-kote (御札籠手)',
    nameItalian: 'I Bracciali Sigillati',
    description:
      'Bracciali in cuoio coperti di Ofuda esauriti cuciti a strati. Richiede Artigiano + Sacerdote per la costruzione.',
    integrityMax: 15,
    effectText:
      'Scudo 4 (T1) · 1/scena annulla 1 attacco onirico (Kyōfu/Kizu), poi −5 Integrità',
    inventorySlotCost: 1,
    isStackable: false,
    priceRem: 45,
  },

  // ─── Veicoli (5) ───
  {
    id: 'equip-tetsuba',
    kind: 'veicolo',
    category: 'equipaggiamento',
    type: 'GENERIC',
    nameRomaji: 'Tetsuba (鉄馬)',
    nameItalian: 'Il Cavallo di Ferro',
    description: 'Moto da enduro del vecchio mondo, rimessa in vita da un Karakurishi.',
    integrityMax: 30,
    effectText: 'Movimento ×4 · 1 persona (2 strette) · consuma carburante',
    inventorySlotCost: 3,
    isStackable: false,
    priceRem: 90,
  },
  {
    id: 'equip-yon-ashi',
    kind: 'veicolo',
    category: 'equipaggiamento',
    type: 'GENERIC',
    nameRomaji: 'Yon-ashi (四脚)',
    nameItalian: 'Il Quattro-Zampe',
    description: 'Quad da lavoro con pianale di carico.',
    integrityMax: 35,
    effectText: 'Movimento ×3 · 2 persone + 4 slot inventario · consuma carburante',
    inventorySlotCost: 4,
    isStackable: false,
    priceRem: 105,
  },
  {
    id: 'equip-yoru-tomo',
    kind: 'veicolo',
    category: 'equipaggiamento',
    type: 'GENERIC',
    nameRomaji: 'Yoru no Tomo (夜の友)',
    nameItalian: 'L\'Amico della Notte',
    description:
      'Cavallo da sella, razza sopravvissuta e riaddomesticata. Creatura: lo cura il medico, non l\'artigiano.',
    integrityMax: 25,
    effectText:
      'Movimento ×3 · 1 persona + 2 slot · HP 25 · 1 Erba comune/giorno · spavento onirico (Fudōshin)',
    inventorySlotCost: 3,
    isStackable: false,
    priceRem: 75,
  },
  {
    id: 'equip-niguruma',
    kind: 'veicolo',
    category: 'equipaggiamento',
    type: 'GENERIC',
    nameRomaji: 'Niguruma (荷車)',
    nameItalian: 'Il Carro del Viandante',
    description: 'Carretto a traino (umano o animale).',
    integrityMax: 25,
    effectText: 'Movimento ×1 a mano, ×2 con Yoru no Tomo · +10 slot inventario',
    inventorySlotCost: 5,
    isStackable: false,
    priceRem: 75,
  },
  {
    id: 'equip-sabi-guruma',
    kind: 'veicolo',
    category: 'equipaggiamento',
    type: 'GENERIC',
    nameRomaji: 'Sabi-guruma (錆車)',
    nameItalian: 'La Carcassa che Cammina',
    description: 'Furgone del vecchio mondo tenuto insieme da saldature e preghiere.',
    integrityMax: 40,
    effectText:
      'Movimento ×3 · 4 persone + 8 slot · molto carburante · avvio incerto (1 quarto, Karakurishi/Shokunin)',
    inventorySlotCost: 5,
    isStackable: false,
    priceRem: 120,
  },
] as const

const catalogById = new Map(MARKET_EQUIPMENT_CATALOG.map((e) => [e.id, e]))

export function getMarketEquipmentDef(id: string): MarketEquipmentDef | undefined {
  return catalogById.get(id)
}

export function marketEquipmentByKind(
  kind: MarketEquipmentKind,
): readonly MarketEquipmentDef[] {
  return MARKET_EQUIPMENT_CATALOG.filter((e) => e.kind === kind)
}
