import {
  faRightFromBracket,
  faUser,
  faMessage,
  faBell,
  faLandmark,
  faShop,
  faBolt,
  faScroll,
  faCloudSun,
  faCalendarDays,
  faUsers,
  faTv,
  faChevronDown,
  faPlay,
  faWindowMinimize,
  faXmark,
  faMapLocationDot,
  faSun,
  faCloud,
  faCloudRain,
  faPaperPlane,
  faChevronLeft,
  faThumbtack,
  faPlus,
  faTrash,
  faBullhorn,
  faTrophy,
  faGamepad,
  faHome,
  faArrowsRotate,
  faHeart,
  faQuoteLeft,
  faLock,
  faLockOpen,
  faCircle,
  faCircleDot,
  faFileLines,
  faPenToSquare,
  faCheck,
  faXmark as faTimes,
  faInfo,
  faExclamation,
} from "@fortawesome/free-solid-svg-icons";

export const icons = {
  logout: faRightFromBracket,
  user: faUser,
  message: faMessage,
  bell: faBell,
  banca: faLandmark,
  shop: faShop,
  waza: faBolt,
  ordine: faScroll,
  weather: faCloudSun,
  calendar: faCalendarDays,
  presenti: faUsers,
  news: faTv,
  abbassare: faChevronDown,
  play: faPlay,
  minimize: faWindowMinimize,
  close: faXmark,
  map: faMapLocationDot,
  sun: faSun,
  cloud: faCloud,
  rain: faCloudRain,
  send: faPaperPlane,
  back: faChevronLeft,
  pin: faThumbtack,
  plus: faPlus,
  trash: faTrash,
  bullhorn: faBullhorn,
  trophy: faTrophy,
  gamepad: faGamepad,
  home: faHome,
  refresh: faArrowsRotate,
  heart: faHeart,
  quote: faQuoteLeft,
  lock: faLock,
  unlock: faLockOpen,
  circle: faCircle,
  circleDot: faCircleDot,
  file: faFileLines,
  edit: faPenToSquare,
  check: faCheck,
  times: faTimes,
  info: faInfo,
  exclamation: faExclamation,
} as const;
