import {
  faRightFromBracket,
  faUser,
  faMessage,
  faBell,
  faLandmark,
  faShop,
  faBasketShopping,
  faBolt,
  faScroll,
  faCloudSun,
  faCalendarDays,
  faUsers,
  faTv,
  faChevronDown,
  faPlay,
  faWindowMinimize,
  faXmark,
  faMapLocationDot,
  faSun,
  faCloud,
  faCloudRain,
  faPaperPlane,
  faChevronLeft,
  faThumbtack,
  faPlus,
  faTrash,
  faBullhorn,
  faTrophy,
  faGamepad,
  faHome,
  faArrowsRotate,
  faHeart,
  faQuoteLeft,
  faLock,
  faLockOpen,
  faCircle,
  faCircleDot,
  faFileLines,
  faPenToSquare,
  faCheck,
  faXmark as faTimes,
  faInfo,
  faExclamation,
  faMagnifyingGlass,
  faEye,
  faEyeSlash,
  faBroom,
  faEraser,
  faDownload,
  faEnvelope,
  faEnvelopeOpen,
  faGear,
  faPencil,
  faFire,
  faCodeBranch,
} from "@fortawesome/free-solid-svg-icons";

export const icons = {
  logout: faRightFromBracket,
  user: faUser,
  message: faMessage,
  envelope: faEnvelope,
  bell: faBell,
  banca: faLandmark,
  shop: faShop,
  mercato: faBasketShopping,
  waza: faBolt,
  ordine: faScroll,
  weather: faCloudSun,
  calendar: faCalendarDays,
  presenti: faUsers,
  news: faTv,
  abbassare: faChevronDown,
  play: faPlay,
  minimize: faWindowMinimize,
  close: faXmark,
  map: faMapLocationDot,
  sun: faSun,
  cloud: faCloud,
  rain: faCloudRain,
  send: faPaperPlane,
  back: faChevronLeft,
  pin: faThumbtack,
  plus: faPlus,
  trash: faTrash,
  bullhorn: faBullhorn,
  trophy: faTrophy,
  gamepad: faGamepad,
  home: faHome,
  refresh: faArrowsRotate,
  heart: faHeart,
  quote: faQuoteLeft,
  lock: faLock,
  unlock: faLockOpen,
  circle: faCircle,
  circleDot: faCircleDot,
  skiru: faCircleDot,
  sokaiju: faCodeBranch,
  file: faFileLines,
  edit: faPenToSquare,
  check: faCheck,
  times: faTimes,
  info: faInfo,
  exclamation: faExclamation,
  search: faMagnifyingGlass,
  eye: faEye,
  eyeSlash: faEyeSlash,
  broom: faBroom,
  clearChat: faEraser,
  download: faDownload,
  envelopeOpen: faEnvelopeOpen,
  gear: faGear,
  pencil: faPencil,
  fire: faFire,
} as const;
