/** Waza Generiche — Parte trasversale ROADMAP_CONTEXT.md (fondamentali + accademia). */
import type { WazaDef } from '../wazaPool'
import { makeActive, makePassive } from './waza-pool-builders'

const B = 'generiche' as const

export const GENERICHE_WAZA_POOL: WazaDef[] = [
  makePassive(
    B,
    'generiche-kajiba-adrenalina',
    'Kajiba (火事場) — Adrenalina',
    'C\'è una soglia oltre la quale il corpo smette di risparmiarsi. La prima ferita che conta davvero spalanca i nuclei oltre la misura abituale: la Jigo-Ka affluisce in eccesso, più di quanta a freddo se ne potrebbe contenere, e la tecnica successiva la scarica tutta in una volta.',
    'Passiva · CS 0. La prima volta che scendi sotto il 50% degli HP in uno scontro, la tua prossima waza sale di 1 tier di danno.',
  ),
  makePassive(
    B,
    'generiche-kazari-monile',
    'Kazari (飾り) — Monile',
    'L\'analista solidifica una piccola quantità di Jigo-Ka in un ornamento da portare addosso: un pendente, un anello, una fibbia — indistinguibile da un gioiello vero finché non gli si chiede di essere altro.',
    'Passiva · CS 0. Generi un piccolo [Costrutto][Solido] (pendente, anello…). Una volta per combattimento può ingrandirsi fino a 1 m; a fine scontro torna normale se intatto.',
  ),
  makePassive(
    B,
    'generiche-yasuragi-balsamo',
    'Yasuragi (安らぎ) — Balsamo dell\'Anima',
    'Forzare i nuclei a produrre senza sosta li lascia vuoti; concedere loro anche un solo turno di quiete li lascia ricostituire la riserva con calma.',
    'Passiva · CS 0. Se concludi il turno senza usare waza, rigeneri +1 CS oltre ai 3 base.',
  ),
  makePassive(
    B,
    'generiche-yakudo-psico-atleta',
    'Yakudō (躍動) — Psico-Atleta',
    'L\'analista impara a scaricare parte della propria Jigo-Ka nei muscoli invece che nelle tecniche, usandola come spinta pura. Non è una tecnica da attivare: è un modo costante di abitare il corpo.',
    'Passiva · CS 0. +1,5 m al Movimento per quarto (cumulativo con Undō) e +2 m all\'altezza/distanza di salto.',
  ),
  makePassive(
    B,
    'generiche-iai-incombenza',
    'Iai (居合) — Incombenza',
    'L\'analista che ha passato un intero turno senza agire accumula una tensione pronta a scaricarsi in un gesto solo. Basta una seconda tecnica, o un danno anticipato sul bersaglio, perché la condizione si spezzi.',
    'Passiva · CS 0. Se (a) il turno scorso non hai usato waza, (b) questo turno ne lanci una sola, (c) il bersaglio non ha ancora subìto tuoi danni → quella waza sale di 1 tier.',
  ),
  makePassive(
    B,
    'generiche-kehai-lettura-flusso',
    'Kehai (気配) — Lettura del Flusso',
    'Ogni fonte di Jigo-Ka lascia nell\'aria una traccia che la pelle dell\'analista impara a riconoscere prima degli occhi. Entro otto metri percepisce direzione e intensità — non la posizione esatta.',
    'Passiva · CS 0. Percepisci direzione e intensità della Jigo-Ka entro 8 m (presenza di altri analisti o creature psichiche).',
  ),
  makeActive(
    B,
    'generiche-shoken-eco-pugno',
    'Shoken (初拳) — Eco del Pugno',
    'La prima tecnica insegnata in accademia: muovere la Jigo-Ka, raccoglierla in un punto, farla erompere. Rudimentale e diretta, ma è la base su cui ogni Via costruisce le proprie meraviglie.',
    'Attiva · [Contatto][Energetica] · Tier base 1 · CS 1 · 1/4. Rivesti una parte del corpo di Jigo-Ka [Energetica] e colpisci a [Contatto]. Danno = tier. Va a segno se prevali nello scambio d\'Indice.',
    { costCs: 1, hasDamage: true, dbw: 1 },
  ),
  makeActive(
    B,
    'generiche-shoheki-barriera',
    'Shōheki (障壁) — Barriera',
    'Invece di concentrare la Jigo-Ka in un punto, distribuirla uniforme su tutto il corpo. Ne nasce un velo d\'energia aderente alla pelle che resta inerte fino all\'impatto e brilla soltanto nell\'istante in cui assorbe il colpo.',
    'Attiva · [Scudo][Energetica] · Tier base 1 · CS 1 · 1/4. Veli il corpo di Jigo-Ka e generi uno [Scudo] con Resistenza = valore-tier.',
    { costCs: 1, durata: 'un_turno' },
  ),
  makeActive(
    B,
    'generiche-shikigami-forma-spirito',
    'Shikigami (式神) — Forma dello Spirito',
    'Tenere la Jigo-Ka coesa e stabile una volta uscita dal corpo. L\'analista la modella nella sagoma di un piccolo animale trasparente che si stacca da lui e avanza per conto proprio.',
    'Attiva · [Costrutto][Energetico] · Tier base 1 · CS 2 · 1/4. Emani un famiglio fantasma (taglia piccola) per 2 turni. Percorre fino a 8 m e attacca una volta per turno in linea retta (danno = tier).',
    { costCs: 2, hasDamage: true, dbw: 1, durata: 'due_turni' },
  ),
  makeActive(
    B,
    'generiche-shinya-dardo-psichico',
    'Shinya (心矢) — Dardo Psichico',
    'L\'analista concentra la Jigo-Ka in un punto davanti a sé e la rilascia come un piccolo proiettile compatto e veloce. Il dardo viaggia in linea retta finché non incontra il primo bersaglio.',
    'Attiva · [Proiettile][Energetica] · Tier base 1 · CS 1 · 1/4. Proietti un dardo in linea retta per 15 m; danno = tier al primo bersaglio colpito.',
    { costCs: 1, hasDamage: true, dbw: 1 },
  ),
  makeActive(
    B,
    'generiche-ippuku-gestione-pressione',
    'Ippuku (一服) — Gestione della Pressione',
    'I nuclei rendono di più quando il corpo non è in tensione. L\'analista compie un gesto che lo allenti anche solo per un istante — una boccata di fumo, uno stiramento, le dita che scrocchiano — e in quella breve tregua la Jigo-Ka torna ad affluire più in fretta del normale. Ma riempire i nuclei oltre la loro capienza ha un prezzo: se il recupero supera la soglia, l\'energia ristagna e si rivolta contro chi la trattiene.',
    'Attiva · [Nessuna][Potenziamento] · CS 0 · 1/4. Compi un gesto rilassante: rigeneri +3 CS. Se questo ti porta oltre la soglia di Overheat (20), ottieni lo status [Sovraccarico].',
    { costCs: 0 },
  ),
  makeActive(
    B,
    'generiche-ukenagashi-parata-perfetta',
    'Ukenagashi (受け流し) — Parata Perfetta',
    'L\'analista smette di pensare all\'attacco e si concentra sull\'arma, pronto a intercettare ciò che sta per arrivare. Non si tratta di bloccare di forza, ma di incontrare il colpo con l\'angolo giusto e scostarlo di lato, lasciandolo proseguire oltre il bersaglio. Riuscirci richiede di prevalere su chi attacca; riuscirci bene scopre la sua guardia, e il contraccolpo che segue trova un varco già aperto.',
    'Attiva · [Contatto][Nessuna] · CS 1 · 1/4 (reattiva). Ti prepari a deviare un attacco fisico o un [Proiettile] in arrivo: confronto d\'Indice (le tue Skiru di parata, es. Hansha, contro Indice/tier dell\'attacco). Se prevali, lo devii — ⚠️ la deviazione non annulla i danni se vieni comunque colpito — e la tua prossima offensiva contro quel bersaglio sale di 1 tier. Richiede un\'arma impugnata.',
    { costCs: 1 },
  ),
  makeActive(
    B,
    'generiche-shukuchi-scatto-potenziato',
    'Shukuchi (縮地) — Scatto Potenziato',
    'L\'analista scarica la Jigo-Ka nelle gambe in un\'unica spinta e copre la distanza prima che l\'occhio riesca a seguirlo. Non è teletrasporto: è uno scatto tanto rapido da lasciare, per una frazione di secondo, un\'immagine residua nel punto da cui è partito. La materia solida resta un limite — muri e ostacoli vanno aggirati, non attraversati.',
    'Attiva · [Movimento][Nessuna] · CS 1 · 1/4. Ti sposti istantaneamente di (Movimento × 2) m nella direzione scelta, lasciando un\'immagine residua. Non attraversa muri o ostacoli solidi.',
    { costCs: 1 },
  ),
  makeActive(
    B,
    'generiche-choyaku-salto-potenziato',
    'Chōyaku (跳躍) — Salto Potenziato',
    'L\'analista infonde la Jigo-Ka nelle gambe e la libera in un balzo che nessun muscolo da solo potrebbe sostenere, raggiungendo tetti, cornicioni e distanze altrimenti impossibili. La stessa energia avvolge la ricaduta e ne dissipa l\'urto: un salto che si chiude senza pagare il prezzo dell\'atterraggio. Le cadute lievi non lasciano segno, quelle gravi pesano la metà.',
    'Attiva · [Movimento][Nessuna] · CS 1 · 1/4. Salto potenziato fino a 4 m in verticale o 8 m in orizzontale. L\'atterraggio è ammortizzato: annulla il danno da cadute lievi e dimezza quello da cadute gravi.',
    { costCs: 1 },
  ),
  makeActive(
    B,
    'generiche-kaginawa-presa-ego',
    'Kaginawa (鉤縄) — Presa dell\'Ego',
    'L\'analista solidifica la Jigo-Ka in un uncino collegato a sé da un filo d\'energia e lo scaglia verso un punto in vista. Se il rampino morde una superficie salda, il filo si tende e all\'analista resta la scelta di come usarlo: strapparsi verso l\'appiglio, oppure tirare verso di sé ciò che vi è agganciato, purché di taglia piccola. Compiuto il suo lavoro, il costrutto si scioglie nell\'aria.',
    'Attiva · [Costrutto][Energetico] · CS 1 · 1/4. Proietti un rampino verso un punto visibile entro 12 m. Se si aggancia a una superficie solida, tiri te stesso verso quel punto oppure trascini verso di te oggetti di taglia [Piccola]. Si dissolve dopo l\'uso.',
    { costCs: 1 },
  ),
  makeActive(
    B,
    'generiche-nenwa-comunicazione-silenziosa',
    'Nenwa (念話) — Comunicazione Silenziosa',
    'L\'analista aggancia la propria Jigo-Ka a quella di un bersaglio che vede, o di cui conosce con esattezza la posizione, e vi fa passare le parole senza pronunciarle. Chi le riceve le avverte come un pensiero che non gli appartiene — estraneo, eppure chiaro e riconoscibile come la voce di chi lo invia. Il canale, però, è a senso unico: il bersaglio non può rispondere allo stesso modo, a meno che non padroneggi anch\'egli la tecnica.',
    'Attiva · [Nessuna] · CS 1 · 1/4. Apri una comunicazione mentale con un bersaglio a vista o di cui conosci la posizione esatta entro 20 m. Parli, lui ti percepisce come un pensiero esterno riconoscibile. Non è telepatia piena: non può risponderti con lo stesso mezzo, a meno che non conosca anch\'egli questa tecnica.',
    { costCs: 1 },
  ),
  makeActive(
    B,
    'generiche-fujin-lama-aria',
    'Fūjin (風刃) — Lama d\'Aria',
    'L\'analista comprime l\'aria attorno alla mano e la libera con un gesto tagliente, scagliando una lama che corre in linea retta. È quasi invisibile a occhio nudo — un\'increspatura nell\'aria più che un oggetto — ma chi ha sensibilità alla Jigo-Ka la percepisce arrivare. Ferisce di taglio chiunque incontri per primo lungo la traiettoria.',
    'Attiva · [Proiettile][Gassosa] · Tier base 1 · CS 1 · 1/4. Lanci una lama d\'aria in linea retta per 15 m; danno = tier al primo bersaglio. Difficile da vedere (percepibile da chi sente la Jigo-Ka).',
    { costCs: 1, hasDamage: true, dbw: 1 },
  ),
  makeActive(
    B,
    'generiche-gasho-ego-cristallino',
    'Gashō (我晶) — Ego Cristallino',
    'L\'analista solidifica un frammento di Jigo-Ka in un cristallo traslucido e lo scaglia contro il bersaglio. La punta è dura e affilata, e ferisce perforando. Se manca il bersaglio e incontra una superficie, vi si conficca e resta lì, un cristallo piantato nel terreno o nel muro, prima di dissolversi col tempo: finché regge, è materia a tutti gli effetti.',
    'Attiva · [Proiettile][Solida] · Tier base 1 · CS 1 · 1/4. Scagli un cristallo in linea retta per 15 m; danno = tier (perforante) al primo bersaglio. Se colpisce una superficie invece di un bersaglio, si conficca e per 3 turni conta come [Costrutto][Solido], poi si dissolve.',
    { costCs: 1, hasDamage: true, dbw: 1, durata: 'tre_turni' },
  ),
  makeActive(
    B,
    'generiche-meidan-sibilo-proiettile',
    'Meidan (鳴弾) — Sibilo Proiettile',
    'L\'analista concentra la Jigo-Ka mentre produce un suono ben udibile — uno schiocco delle dita, della lingua, dell\'acciaio — e su quel segnale acustico la libera. Dal suono nasce un proiettile che parte nella direzione scelta e corre dritto fino al bersaglio. L\'innesco sonoro lo rende difficile da anticipare: quando lo si sente, è già partito.',
    'Attiva · [Proiettile][Sonoro] · Tier base 1 · CS 1 · 1/4. Su un suono che produci, lanci un proiettile per 15 m nella direzione scelta; danno = tier al primo bersaglio.',
    { costCs: 1, hasDamage: true, dbw: 1 },
  ),
  makeActive(
    B,
    'generiche-rasui-trivella-psionica',
    'Rasui (螺錐) — Trivella Psionica',
    'L\'analista materializza un\'asta di materia compressa che si allunga rapidamente in avanti ruotando su sé stessa come una punta da trapano. La trivella cresce nella direzione scelta, fora il primo bersaglio che incontra e poi si dissolve. È il raggio più meccanico del repertorio: non brucia né lacera, perfora.',
    'Attiva · [Raggio][Solido] · Tier base 2 · CS 2 · 1/4. Una trivella rotante si estende per 8 m in linea retta; danno = tier (perforante) al primo bersaglio, poi scompare.',
    { costCs: 2, hasDamage: true, dbw: 2 },
  ),
  makeActive(
    B,
    'generiche-funki-bollore-onirico',
    'Funki (噴気) — Bollore Onirico',
    'L\'analista rilascia un\'eruzione istantanea di gas ad altissima pressione in una direzione a scelta. Il getto si estende in linea retta come un soffio violento, investe ciò che incontra e lo respinge per la forza stessa con cui esce. Più che ferire, sfonda e allontana.',
    'Attiva · [Raggio][Gassoso] · Tier base 2 · CS 2 · 1/4. Getto di gas in linea retta per 10 m; danno = tier e sbalzo di 4 m indietro al primo bersaglio (lungo la direzione del getto).',
    { costCs: 2, hasDamage: true, dbw: 2 },
  ),
  makeActive(
    B,
    'generiche-suishin-acupressione-liquida',
    'Suishin (水針) — Acupressione Liquida',
    'L\'analista proietta un getto di liquido ultra-concentrato ad altissima pressione, sottile e preciso come un ago. Non è un\'ondata: è un filo d\'acqua tagliente che incide il primo bersaglio lungo la linea di tiro. La ferita che lascia continua a sanguinare.',
    'Attiva · [Raggio][Liquido] · Tier base 2 · CS 2 · 1/4. Filo di liquido in linea retta per 15 m; danno = tier al primo bersaglio e applica lo status [Emorragia].',
    { costCs: 2, hasDamage: true, dbw: 2 },
  ),
  makeActive(
    B,
    'generiche-fukyoon-dissonanza',
    'Fukyōon (不協音) — Dissonanza',
    'L\'analista emette un fascio di onde sonore concentrate a una frequenza distruttiva, indirizzandolo in linea retta. Il fascio non è un punto ma una colonna di suono che investe il primo bersaglio e tutto ciò che gli sta stretto attorno. Dove passa, l\'aria stessa vibra fino a far male.',
    'Attiva · [Raggio][Sonoro] · Tier base 2 · CS 2 · 1/4. Fascio sonoro in linea retta per 15 m, raggio 2 m; danno = tier al primo bersaglio investito.',
    { costCs: 2, hasDamage: true, dbw: 2 },
  ),
  makeActive(
    B,
    'generiche-hibana-scintilla-ego',
    'Hibana (火花) — Scintilla d\'Ego',
    'L\'analista proietta un fascio elementale concentrato in linea retta, lanciato ad alta velocità verso il bersaglio. Veste la Jigo-Ka del proprio elemento e la spara come un dardo di luce densa. Veloce e lineare, è il raggio elementale di base da cui partono le varianti più elaborate.',
    'Attiva · [Raggio][Energetico] · Tier base 2 · CS 2 · 1/4. Fascio elementale in linea retta per 20 m; danno = tier al primo bersaglio.',
    { costCs: 2, hasDamage: true, dbw: 2 },
  ),
  makeActive(
    B,
    'generiche-sandan-shrapnel-psichico',
    'Sandan (散弾) — Shrapnel Psichico',
    'L\'analista materializza un ventaglio di schegge solide e lo libera tutto in una volta in un cono davanti a sé. Le schegge si aprono a raggiera coprendo l\'intero arco frontale e colpiscono chiunque vi si trovi. È una tecnica d\'area grezza, fatta per saturare lo spazio vicino più che per centrare un singolo nemico.',
    'Attiva · [Propagazione Conica][Solido] · Tier base 2 · CS 2 · 1/4. Cono frontale di 6 m; danno = tier a ogni bersaglio nell\'area.',
    { costCs: 2, hasDamage: true, dbw: 2 },
  ),
  makeActive(
    B,
    'generiche-bakufu-decompressione-onirica',
    'Bakufū (爆風) — Decompressione Onirica',
    'L\'analista rilascia di colpo il gas compresso accumulato nel corpo, scaricandolo in un cono frontale. L\'onda di pressione investe tutta l\'area davanti a lui, colpendo e spingendo via chiunque ne sia preso. Pulisce lo spazio immediato tanto quanto lo danneggia.',
    'Attiva · [Propagazione Conica][Gassoso] · Tier base 2 · CS 2 · 1/4. Cono frontale di 6 m; danno = tier a ogni bersaglio nell\'area e sbalzo di 4 m indietro.',
    { costCs: 2, hasDamage: true, dbw: 2 },
  ),
  makeActive(
    B,
    'generiche-nenmo-ragnatela-mercurio',
    'Nenmō (粘網) — Ragnatela di Mercurio',
    'L\'analista proietta un ventaglio di liquido viscoso e denso, simile a una rete lanciata in un cono davanti a sé. Il liquido investe i bersagli e ne impasta i movimenti, poi ricade a terra restando come una pozza appiccicosa che continua a intralciare chi vi cammina. Non uccide: rallenta, blocca, tiene fermo abbastanza a lungo.',
    'Attiva · [Propagazione Conica][Liquido] · Tier base 2 · CS 2 · 1/4. Cono frontale di 6 m; danno = tier a ogni bersaglio e applica [Rallentato] (−2 m Movimento) per 2 turni. Il liquido resta a terra come zona viscosa per 2 turni: chi la tocca o vi termina il turno subisce lo stesso rallentamento.',
    { costCs: 2, hasDamage: true, dbw: 2, durata: 'due_turni' },
  ),
  makeActive(
    B,
    'generiche-kyokan-urlo-lobo-frontale',
    'Kyōkan (叫喚) — Urlo del Lobo Frontale',
    'L\'analista emette un\'onda sonora concentrata in un cono frontale, un urlo psichico che non passa per la gola ma direttamente per la Jigo-Ka. Il suono investe tutti i bersagli davanti a lui, e chi lo incassa perde l\'equilibrio e l\'orientamento. Più che ferire la carne, scuote la mente.',
    'Attiva · [Propagazione Conica][Sonoro] · Tier base 2 · CS 2 · 1/4. Cono frontale di 6 m; danno = tier a ogni bersaglio e applica [Vertigini] (1 stack).',
    { costCs: 2, hasDamage: true, dbw: 2 },
  ),
  makeActive(
    B,
    'generiche-kyoshin-frequenza-disarmante',
    'Kyōshin (共振) — Frequenza Disarmante',
    'L\'analista fa vibrare le proprie ossa a una frequenza precisa e la trasmette al bersaglio attraverso il contatto fisico. La vibrazione si annida nel corpo altrui e ne disturba il flusso: la prossima tecnica gli costerà più fatica del dovuto. E se il bersaglio non la scarica usando una waza, la frequenza trattenuta finisce per ferirlo da sola.',
    'Attiva · [Contatto][Sonoro] · CS 2 · 1/4. A contatto, impianti una vibrazione: la prossima waza del bersaglio costa +2 CS. La vibrazione svanisce quando il bersaglio usa una waza; se passa un suo intero turno senza usarne, subisce danno = tier.',
    { costCs: 2, hasDamage: true, dbw: 2 },
  ),
  makeActive(
    B,
    'generiche-dendo-propagazione-acustica',
    'Dendō (伝導) — Propagazione Acustica',
    'L\'analista scarica un\'onda sonora non nell\'aria ma nella materia solida su cui poggia — pavimento, muro, soffitto — e la fa correre lungo la superficie in un cerchio che si allarga. Chiunque sia in contatto con quella superficie lungo il percorso viene raggiunto dalla vibrazione. Chi si è staccato da terra, invece, non sente nulla.',
    'Attiva · [Emanazione][Sonoro] · Tier base 2 · CS 2 · 1/4. Un\'onda si propaga lungo una superficie solida per 8 m in cerchio; danno = tier a ogni bersaglio a contatto con la superficie lungo il percorso. Non si propaga nell\'aria.',
    { costCs: 2, hasDamage: true, dbw: 2 },
  ),
  makeActive(
    B,
    'generiche-hankyo-eco-astio',
    'Hankyō (反響) — Eco dell\'Astio',
    'L\'analista sceglie un punto a distanza e vi fa detonare un\'esplosione sonora che si diffonde in ogni direzione. Non parte da lui ma dal punto designato, raggiungendo bersagli che un cono frontale non toccherebbe. Chi ne è investito incassa il colpo e ne esce stordito.',
    'Attiva · [Emanazione a distanza][Sonoro] · Tier base 2 · CS 2 · 1/4. Scegli un punto entro 12 m: esplosione sonora in tutte le direzioni, raggio 4 m; danno = tier e [Vertigini] (1 stack) a ogni bersaglio nell\'area.',
    { costCs: 2, hasDamage: true, dbw: 2 },
  ),
  makeActive(
    B,
    'generiche-kiho-bolla-pressurizzata',
    'Kihō (気泡) — Bolla Pressurizzata',
    'L\'analista comprime gas psichico in una bolla sferica davanti a sé, una membrana tesa che fa da scudo finché regge. Quando cede, però, non si limita a rompersi: il gas trattenuto si libera di colpo in un\'esplosione di pressione che respinge tutto ciò che le sta intorno. Una difesa che, nel rompersi, contrattacca.',
    'Attiva · [Scudo][Gassoso] · CS 2 · 1/4. Generi una bolla (∅ ~2 m) con Resistenza = valore-tier. Quando viene distrutta, il gas si rilascia sbalzando di 4 m indietro tutto ciò che si trova entro 3 m dal punto di rottura.',
    { costCs: 2, dbw: 2 },
  ),
  makeActive(
    B,
    'generiche-suimaku-velo-liquido',
    'Suimaku (水幕) — Velo Liquido',
    'L\'analista genera davanti a sé una cortina di liquido psichico denso, una lastra d\'acqua sospesa che frena ciò che la attraversa. I proiettili che la perforano ne escono più lenti e più deboli, avendo speso parte della loro spinta nel liquido. Se la cortina sopravvive al colpo, resta su fino alla fine del turno.',
    'Attiva · [Scudo][Liquido] · CS 2 · 1/4. Crei una cortina (~3×3 m) con Resistenza = valore-tier. I [Proiettili] che la attraversano subiscono −4 danno e −5 m di gittata rimanente. Se il velo sopravvive al colpo, permane fino alla fine del tuo turno.',
    { costCs: 2, dbw: 2, durata: 'un_turno' },
  ),
  makeActive(
    B,
    'generiche-funshutsu-eruzione-ego',
    'Funshutsu (噴出) — Eruzione dell\'Ego',
    'L\'analista lascia erompere la propria Jigo-Ka da tutto il corpo in una volta sola, scaricandola in ogni direzione come un\'onda elementale. Non sceglie un bersaglio: colpisce tutto ciò che gli sta vicino, amici e nemici senza distinzione. È la tecnica della disperazione e dello spazio da liberare a ogni costo.',
    'Attiva · [Energetica][Emanazione] · Tier base 3 · CS 3 · 1/4. Esplosione elementale in tutte le direzioni, raggio 5 m; danno = tier a ogni bersaglio nell\'area (te escluso).',
    { costCs: 3, hasDamage: true, dbw: 3 },
  ),
]
