/** Genzai-dō (現在道) — Parte III Oyasumi_Manuale_Completo.pdf + waza avanzate ROADMAP (23 waza). */
import type { WazaDef } from '../wazaPool'
import { makeActive, makePassive } from './waza-pool-builders'

const B = 'materializzazione' as const

export const GENZAI_WAZA_POOL: WazaDef[] = [
  makePassive(
    B,
    'nikutai-mei-carne-iscritta',
    'Nikutai-Mei (肉体銘) — Carne Iscritta',
    "Dove c'era carne, l'analista incide struttura: l'arto perduto torna come sigillo, fedele alla memoria di ciò che era.",
    'Passiva · CS 0. Rimpiazzi parti del corpo con un Costrutto Solido dalla forma esatta della parte mancante. Quando quella parte viene colpita, il dolore fantasma drena CS invece di HP.',
  ),
  makePassive(
    B,
    'honshitsu-essenza-affine',
    'Honshitsu (本質) — Essenza Affine',
    "Un solo elemento è inscritto nell'analista, per sempre, e da lui sgorga in ogni cosa che scrive.",
    'Passiva · CS 0, keystone elementale. Scegli un elemento, immutabile. Puoi infonderlo nei tuoi Costrutti Solidi (ne assumono le proprietà) e nelle tue waza Energetiche (diventano Elementali col relativo status). È il presupposto delle waza elementali dello Stile.',
  ),
  makePassive(
    B,
    'kochiku-struttura-salda',
    'Kōchiku (構築) — Struttura Salda',
    'Le linee del sigillo, tracciate fitte, reggono più peso.',
    'Passiva · CS 0. I tuoi Costrutti e Scudi Solidi ottengono +1 tier di Resistenza.',
  ),
  makePassive(
    B,
    'bugusho-arsenale-scritto',
    'Bugusho (武具書) — Arsenale Scritto',
    'Tre frasi affilate, tracciate tra le dita, pronte a infrangersi su ciò che colpiscono.',
    'Passiva · CS 0. Crei tra le mani 3 armi piccole, Costrutti Energetici (aghi, coltelli...), che si infrangono al primo ostacolo fisico. Una sola può restare nascosta 6 ore; lanciando una waza, tutte spariscono.',
  ),
  makePassive(
    B,
    'kaihen-forgia-ibrida',
    'Kaihen (改編) — Forgia Ibrida',
    'Due armi, una sola sentenza: corpo dell\'una, morso dell\'altra.',
    'Passiva · CS 0. Crei un oggetto di media taglia, Costrutto Solido, fusione di due armi (corpo di una, estremità dell\'altra). Una per quest; usando entrambe le estremità, si rompe a fine secondo turno.',
  ),
  makePassive(
    B,
    'kioku-mei-sigillo-mnemonico',
    'Kioku-Mei (記憶銘) — Sigillo Mnemonico',
    'Ciò che si è scritto bene una volta, si riscrive senza fatica.',
    'Passiva · CS 0. Ricreare un Costrutto già creato (stessa forma e dimensione) costa −1 CS. Memorizzi fino a 3 forme; memorizzarne una richiede di averla creata almeno 3 volte.',
  ),
  makePassive(
    B,
    'eizoku-sigillo-persistente',
    'Eizoku (永続) — Sigillo Persistente',
    'Un sigillo ben tracciato non sbiadisce in fretta.',
    'Passiva · CS 0. I tuoi Costrutti durano +1 turno. Quando uno sta per dissolversi, puoi spendere metà del suo costo in CS per estenderne la durata invece di ricrearlo.',
  ),
  makePassive(
    B,
    'kaju-sovraccarico-geometrico',
    'Kajū (過重) — Sovraccarico Geometrico',
    "L'analista calca la scrittura finché trafigge ciò che dovrebbe fermarla.",
    'Passiva · CS 0 (+1 CS opzionale). Lanciando una waza Solida, paghi +1 CS per ignorare il 25% della Resistenza del primo ostacolo (dimezzato, 12,5%, sui viventi). Cumulabile per ogni CS speso.',
  ),
  makePassive(
    B,
    'hakai-mei-marchio-del-disfacimento',
    'Hakai-Mei (破壊銘) — Marchio del Disfacimento',
    "Chi scrive il reale sa anche cancellarlo: contro l'opera altrui, la sua mano è più dura.",
    'Passiva · CS 0. +1 tier di danno contro i Costrutti.',
  ),
  makePassive(
    B,
    'irekogo-sigillo-annidato',
    'Irekogo (入れ子) — Sigillo Annidato',
    'Un guscio scritto attorno a un altro: il primo cade, e sotto attende ciò che era nascosto.',
    'Passiva · CS 0. "Rivesti" un tuo Costrutto Solido con un altro tuo Costrutto: il guscio esterno fa da scudo finché regge, poi si dissolve rivelando l\'interno già pronto.',
  ),
  makeActive(
    B,
    'toki-aura-dichiarata',
    'Tōki (闘気) — Aura Dichiarata',
    "L'analista rende visibile ciò che gli circola dentro: l'aura si fa materia, scudo o lancia.",
    'Attiva · [Energetica] · Tier base 2 · CS 2 · 1/4. Armatura: l\'aura diventa un Costrutto Solido avvolgente, fisso fino a morte o grande mutamento psichico; conta come Scudo con Resistenza scala-tier e concede +5% di mitigazione finché regge. Proiettile, in alternativa: l\'aura defluisce in un arto e si libera in un Proiettile Energetico (sfera 5×5), gittata 15 m, danno = tier.',
    { costCs: 2, hasDamage: true },
  ),
  makeActive(
    B,
    'raimei-fu-sigillo-del-fulmine',
    'Raimei-Fu (雷鳴符) — Sigillo del Fulmine',
    'Un punto segnato a terra, e il cielo è costretto a rispondere.',
    'Attiva · [Costrutto][Elementale] · Tier base 3 · CS 3 · 1/4. Scegli un punto entro 12 m: un fulmine cade colpendo entro 3 m dall\'impatto (danno = tier, applica status). +2 CS per un secondo punto.',
    { costCs: 3, hasDamage: true },
  ),
  makeActive(
    B,
    'yoki-no-iki-soffio-yokai',
    'Yōki no Iki (妖気の息) — Soffio dello Yōkai',
    "Dal respiro dell'analista esala una nebbia che annebbia i sensi e attende solo una scintilla.",
    'Attiva · [Emanazione][Gassosa] · Tier base 2 · CS 2 · 1/4. Nube per 4 m attorno a te, permane 2 turni. Dentro, i bersagli subiscono −3 all\'Indice delle azioni di Riflessi (Hansha). Infiammabile: a contatto con Fuoco o Fulmine s\'incendia e sparisce nel turno.',
    { costCs: 2, durata: 'due_turni' },
  ),
  makeActive(
    B,
    'onnen-dama-globo-rancore',
    'Onnen-dama (怨念玉) — Globo del Rancore',
    "Una sfera di astio fluttua accanto all'analista, e si avventa su chiunque osi colpirlo.",
    'Attiva · [Costrutto][Energetico] · Tier base 2 · CS 2 · 1/4 + mantenimento. Generi un globo che ti segue per 4 turni; si lancia automaticamente verso la prima fonte di danno subìta, poi esplode in Emanazione a distanza (area 3 m, danno = tier). Si muove a 6 m a turno; oltre la gittata diventa Proiettile e si schianta dritto, con danno e area maggiorati.',
    { costCs: 2, hasDamage: true, durata: 'quattro_turni' },
  ),
  makeActive(
    B,
    'hashira-colonne-incise',
    'Hashira (柱) — Colonne Incise',
    'Due colonne si scrivono dal suolo, pazienti come pilastri di un tempio.',
    'Attiva · [Costrutto] · Tier base 2 · CS 2 · 1/4. Due colonne emergono dal terreno (pietra, cemento, detriti...), alte 5 m, larghe 1 m, distanti 1 m fra loro e sulla stessa linea; permangono 3 turni.',
    { costCs: 2, durata: 'tre_turni' },
  ),
  makeActive(
    B,
    'utsushi-copia-conforme',
    'Utsushi (写し) — Copia Conforme',
    "L'analista riscrive la stessa frase due volte: due realtà identiche, una appena più breve.",
    'Attiva · [Nessuna] · CS 2 · 1/4. Copia un tuo Costrutto (stessa consistenza, taglia, forma e Resistenza; eredita effetti e status attivi). Durata = quella base meno 1 turno. Usabile anche durante una creazione: la copia appare entro 3 m dall\'originale.',
    { costCs: 2 },
  ),
  makeActive(
    B,
    'shogeki-te-palmo-elementale',
    'Shōgeki-Te (衝撃手) — Palmo Elementale',
    'La mano si vela di un liquido psichico denso e marchia ciò che tocca.',
    'Attiva · [Contatto][Elementale] · Tier base 1 · CS 1 · 1/4. Colpisci a contatto: danno = tier, applica lo status dell\'elemento affine. Richiede Honshitsu.',
    { costCs: 1, hasDamage: true },
  ),
  makeActive(
    B,
    'genso-ya-dardo-elementale',
    'Genso-Ya (元素矢) — Dardo Elementale',
    'Un dardo del proprio elemento, scritto e scoccato in un sol gesto.',
    'Attiva · [Proiettile][Elementale] · Tier base 1 · CS 1 · 1/4. Proiettile dell\'elemento affine in linea retta, gittata 15 m: danno = tier al primo bersaglio, applica status. Richiede Honshitsu.',
    { costCs: 1, hasDamage: true },
  ),
  makeActive(
    B,
    'kessho-mei-memento-mori',
    'Kesshō-Mei (結晶銘) — Memento Mori',
    'L\'analista solidifica il veleno che già scorre nel nemico, e lo trasforma in una lapide che lo insegue.',
    'Attiva · [Contatto] → [Costrutto][Elementale] · Tier base 3 · CS 3 · 1/4. Tocchi un vivente con almeno 1 stack di status elementale: rimuovi tutte le stack e generi un Costrutto Elementale di taglia proporzionale (1-2 stack = Piccola, 3-4 = Media, 5+ = Grande). Il costrutto segue il bersaglio a 3 m; distrutto, esplode (danno = tier per taglia) e ridistribuisce le stack sui bersagli in gittata.',
    { costCs: 3, hasDamage: true },
  ),
  makeActive(
    B,
    'jiban-terreno-ostile',
    'Jiban (地盤) — Terreno Ostile',
    "Il suolo stesso viene riscritto: ciò che era terra diventa l'elemento dell'analista.",
    'Attiva · [Propagazione][Elementale] · Tier base 2 · CS 2 · 1/4. Ricopri il terreno in un\'area di 4 m attorno a un punto entro 8 m col tuo elemento affine: zona Propagazione Elementale per 3 turni. Chi vi sta o la attraversa subisce lo status. L\'analista è immune.',
    { costCs: 2, hasDamage: true, durata: 'tre_turni' },
  ),
  makeActive(
    B,
    'meisaku-opera-prima',
    'Meisaku (銘作) — Opera Prima',
    "L'analista non scrive una frase: scrive la frase. Le linee si tracciano fitte e lente, geometria precisa e caotica insieme, finché il sigillo si chiude su sé stesso e non sbiadisce più. È il gesto di Tenkan, la Corona che nomina, portato fino in fondo: una cosa dichiarata esistente che il mondo non riesce più a dimenticare. Finché la regge, Shiju non ha presa su di lei.",
    "Attiva · [Costrutto][Solido] · CS 6 · 2/4 (scrittura precisa) · grado richiesto: Sentatsu Bunsekikan [SB]. Materializzi la tua Opera Prima, un [Costrutto][Solido] permanente e unico (una sola attiva alla volta). Resistenza tier 5 (23); forma a tua scelta, fissata alla creazione; taglia fino a [Grande]. Il suo Mei è inviolabile: non conta nel limite Gosa e non è mai il sigillo che si incrina. Non si dissolve col tempo. Se distrutta, puoi ri-dichiararla — stessa Opera Prima — dedicando un turno intero e pagandone di nuovo il costo.",
    { costCs: 6, costJigo: () => 12, hasDamage: false, prereqGradoMin: 4 },
  ),
  makeActive(
    B,
    'shinryaku-invasione',
    'Shinryaku (侵略) — Invasione',
    "Non un disegno paziente, ma uno strappo. L'analista punta un dito e la realtà, in quel punto, è costretta a far spazio: una massa solida si scrive tutta in una volta, con un suono secco, scaraventando via ciò che occupava il posto. È creazione oltre l'umano — non si chiede permesso al mondo, lo si occupa.",
    "Attiva · [Costrutto][Solido] · Tier base 5 · CS 7 · 1/4 · grado richiesto: Kanteikan [K]. Materializzi istantaneamente un [Costrutto][Solido] di taglia [Grande] in un punto visibile entro 12 m. Tutto ciò che occupa il punto è investito dall'apparizione: i bersagli a contatto subiscono danno = tier (23) e sono sbalzati di 4 m; ogni [Costrutto] di taglia inferiore alla [Grande] nel punto viene distrutto. Il costrutto generato dura 3 turni, ha Resistenza tier 4 (17), forma a tua scelta.",
    { costCs: 7, costJigo: () => 14, hasDamage: true, durata: 'tre_turni', prereqGradoMin: 5 },
  ),
  makeActive(
    B,
    'rakuen-eden',
    'Rakuen (楽園) — Eden',
    "L'analista smette di scrivere sul mondo e comincia a scrivere il mondo. Imprime il proprio Ego sulla realtà attorno a sé: il suolo si riveste della sua geometria, ogni superficie si incide del suo Mei, la luce prende il colore della sua Jigo-Ka. Dentro questo cerchio non esiste più il margine d'errore — ciò che traccia non scivola verso Shiju, perché qui Shiju non è mai stato invitato.",
    "Attiva · [Emanazione][Nessuna] · CS 8 + mantenimento · 1/4 · grado richiesto: Shin'enkan [S]. Per 4 turni, l'area in raggio 10 m attorno a te (ti segue) diventa il tuo mondo interiore reso tangibile. Entro l'Eden:\n\n— i tuoi [Costrutti] non si dissolvono (permangono oltre la scadenza normale finché l'Eden regge) e il limite Gosa è sospeso — nessun Mei si incrina;\n\n— ogni tuo [Costrutto] distrutto viene rigenerato all'inizio del tuo turno successivo al costo di 2 CS ciascuno;\n\n— hai percezione continua della posizione di ogni essere vivente nell'Eden.",
    { costCs: 8, costJigo: () => 16, costJigoTipo: 'mantenimento', durata: 'quattro_turni', prereqGradoMin: 6 },
  ),
]
