/** Hadō-dō (波動道) — Parte III Oyasumi_Manuale_Completo.pdf + waza avanzate ROADMAP (22 waza). */
import type { WazaDef } from '../wazaPool'
import { makeActive, makePassive } from './waza-pool-builders'

const B = 'emissione' as const

export const HADO_WAZA_POOL: WazaDef[] = [
  makePassive(
    B,
    'chikuden-batteria',
    'Chikuden (蓄電) — Batteria',
    "L'analista lascia parte di sé dentro un oggetto: una carica latente che aspetta solo di essere ripresa — o di esplodere.",
    'Passiva · CS 0, applica il tag Batteria. Depositi fino a 5 CS in un tuo Costrutto, che le trattiene a lungo; le riprendi, in tutto o in parte, toccandolo. È la keystone di tutte le interazioni con il tag Batteria.',
  ),
  makePassive(
    B,
    'gyakuryu-riflusso',
    'Gyakuryū (逆流) — Riflusso',
    'Ciò che porta la tua energia, torna a te per la via più rapida.',
    'Passiva · CS 0. Richiami a te un Costrutto permeato della tua energia: torna in mano per la traiettoria più veloce. Armi piccole o medie tornano istantaneamente; oggetti più grandi a discrezione della distanza e delle circostanze.',
  ),
  makePassive(
    B,
    'teishuha-onda-bassa',
    'Teishūha (低周波) — Onda Bassa',
    'Una pulsazione invisibile esplora lo spazio e ti rivela ogni fonte d\'energia.',
    'Passiva · CS 0. Espandi una sfera d\'energia invisibile per 8 m: rivela ogni fonte di Jigo-Ka nel raggio (chi è investito sente un lieve tepore). Usabile attraverso un tuo Costrutto entro 8 m; se ha il tag Batteria, la gittata raddoppia.',
  ),
  makePassive(
    B,
    'kanshi-occhio-remoto',
    'Kanshi (監視) — Occhio Remoto',
    'Chiudi gli occhi, e vedi da altrove.',
    'Passiva · CS 0. Depositi energia in un tuo Costrutto, che la trattiene un paio d\'ore; chiudendo entrambi gli occhi ottieni vista e udito completi dal punto di vista del Costrutto.',
  ),
  makePassive(
    B,
    'fuantei-deflagrazione-instabile',
    'Fuantei (不安定) — Deflagrazione Instabile',
    'Nessun colpo si limita a colpire: lascia dietro di sé un\'eco che esplode.',
    'Passiva · CS 0 (+1 CS al lancio). Al lancio paghi +1 CS per un effetto aggiuntivo secondo la categoria: Proiettile → esplosione all\'impatto (stessa consistenza, 3 m); Raggio → colpo concatenato a un altro bersaglio entro 6 m; Emanazione, Propagazione Conica o Emissione a distanza → +4 m di gittata.',
  ),
  makePassive(
    B,
    'kaatsu-sovrapressione',
    'Kaatsu (加圧) — Sovrapressione',
    'Più trattieni, più ciò che esce fa male.',
    'Passiva · CS 0. È l\'innesco della meccanica Atsuryoku: quando sei in Pressione (CS ≥ 12), la prossima waza Emanazione, Propagazione o Energetica ottiene +1 tier. Cumulabile con altri bonus.',
  ),
  makePassive(
    B,
    'kantsu-calibro-pesante',
    'Kantsū (貫通) — Calibro Pesante',
    'Il raggio non si ferma: trapassa e prosegue.',
    'Passiva · CS 0. Una tua waza Raggio non si arresta al primo bersaglio: prosegue infliggendo −25% di danno a ogni bersaglio successivo.',
  ),
  makePassive(
    B,
    'sorashi-deviazione',
    'Sorashi (逸らし) — Deviazione',
    "L'onda non para né schiva: scosta.",
    'Passiva · CS 0 (costo variabile). Su una tua Propagazione Conica o Emanazione, paghi +1 CS per deviare ogni oggetto di taglia Piccola incontrato, +3 CS per allontanare uno di taglia Media. Non è parata né schivata: è deviazione, con esiti variabili.',
  ),
  makePassive(
    B,
    'howa-saturazione',
    'Hōwa (飽和) — Saturazione',
    'Il secondo colpo trova la breccia aperta dal primo.',
    'Passiva · CS 0. Se colpisci lo stesso bersaglio con 2 waza nello stesso turno, la seconda ottiene +1 tier di danno.',
  ),
  makePassive(
    B,
    'fukitobashi-spinta-urto',
    'Fukitobashi (吹き飛ばし) — Spinta d\'Urto',
    'Ogni proiettile è anche un pugno d\'aria che spazza via.',
    'Passiva · CS 0. Le tue waza Proiettile creano all\'impatto una zona di 3 m che spinge via di 4 m chiunque sia a gittata.',
  ),
  makeActive(
    B,
    'tanraku-corto-circuito',
    'Tanraku (短絡) — Corto Circuito',
    "L'analista riversa la sua energia in un oggetto fino a renderlo una bomba.",
    'Attiva · [Energetiche][Contatto] · Tier base 2 · CS 2 · 1/4. Sovraccarichi un Costrutto o oggetto finché diventa instabile; a comando o per forte impatto esplode: danno = tier in 3 m. Se ha il tag Batteria, l\'esplosione si allarga di 2 m; se colpisce un altro Batteria, quello esplode a metà raggio.',
    { costCs: 2, hasDamage: true },
  ),
  makeActive(
    B,
    'hosha-raffica-psichica',
    'Hōsha (放射) — Raffica Psichica',
    'Dai palmi e dalle piante, l\'energia erompe in una scarica di colpi.',
    'Attiva · [Proiettile][Energetico] · Tier base 2 · CS 2 · 1/4. Liberi 2 Proiettili Energetici per 15 m, danno = tier ciascuno.',
    { costCs: 2, hasDamage: true },
  ),
  makeActive(
    B,
    'tameru-impeto-trattenuto',
    'Tameru (溜め) — Impeto Trattenuto',
    'Comprime, comprime ancora — e poi cede.',
    'Attiva · [Emanazione][Energetica] · Tier base 2 · CS 2 · 1/4 + carica. Comprimi la Jigo-Ka fino a 2 turni, rilasciabile in qualsiasi momento, in una forza repulsiva per 5 m. Nello stesso turno interrompe o compromette i movimenti attorno, senza danno; al secondo turno è più forte, danno = tier. Se vieni colpito mentre carichi, l\'impeto si rilascia prematuramente e ne sei vittima anche tu.',
    { costCs: 2, hasDamage: true, durata: 'due_turni' },
  ),
  makeActive(
    B,
    'hoden-scarica-impatto',
    'Hōden (放電) — Scarica d\'Impatto',
    "L'energia accumulata in un arto si scarica al contatto, sfondando tutto.",
    'Attiva · [Contatto][Energetica] · Tier base 2 · CS 2 · 1/4. Carichi una parte del corpo; all\'impatto scarichi un\'onda d\'urto per 4 m che danneggia (= tier) e compromette la stabilità, sfondando pareti, costrutti, ossa. Se non scarichi entro il turno, quella parte del corpo subisce danno = tier.',
    { costCs: 2, hasDamage: true },
  ),
  makeActive(
    B,
    'mugen-no-tsukai-famiglio-onirico',
    'Mugen no Tsukai (夢幻の使い) — Famiglio Onirico',
    "L'analista scinde da sé un frammento vivo della propria energia.",
    'Attiva · [Costrutto][Energetico] · Tier base 2 · CS 2 · 1/4. Dai vita a un famiglio (animale, taglia media) per 3 turni; durante, non guadagni CS a inizio turno. Percorre 8 m e attacca una volta per turno (danno = tier). Se acquisisce un elemento, lo mantiene fino a fine tecnica.',
    { costCs: 2, hasDamage: true, durata: 'tre_turni' },
  ),
  makeActive(
    B,
    'rensa-baku-detonazione-catena',
    'Rensa-Baku (連鎖爆) — Detonazione a Catena',
    'Tutto ciò che porta la sua firma esplode nello stesso istante.',
    'Attiva · [Emanazione a distanza][Energetica] · Tier base 3 · CS 3 · 1/4. Selezioni fino a 3 tuoi Costrutti con tag Batteria a vista: esplodono simultaneamente, ognuno come Tanraku. Le zone sovrapposte subiscono danni aumentati.',
    { costCs: 3, hasDamage: true },
  ),
  makeActive(
    B,
    'kasan-carica-detonante',
    'Kasan (加算) — Carica Detonante',
    'Un colpo che non ferisce: aggrava.',
    'Attiva · [Potenziamento][Nulla] · Tier base 2 · CS 2 · 1/4. La prossima waza dà al bersaglio +1 stack di uno status che già possiede, a tua scelta. Se il bersaglio ha almeno 5 stack di uno status, infliggi danno = tier.',
    { costCs: 2, hasDamage: true },
  ),
  makeActive(
    B,
    'byo-ancora-psionica',
    'Byō (鋲) — Ancora Psionica',
    'Un punto fisso nello spazio a cui i tuoi colpi obbediscono.',
    'Attiva · [Costrutto][Energetico] · CS 1 · 1/4. Imprimi su una superficie un piccolo Costrutto invisibile. Per 3 turni, le tue waza Proiettile o Raggio possono sceglierlo come bersaglio finale, aggirando gli ostacoli entro i limiti di gittata.',
    { costCs: 1, durata: 'tre_turni' },
  ),
  makeActive(
    B,
    'maikomi-innesto-forzato',
    'Maikomi (埋め込み) — Innesto Forzato',
    'Pianti una carica e scegli tu quando il mondo cede.',
    'Attiva · [Emanazione a distanza][Energetica] · Tier base 3 · CS 3 · 1/4. Tocchi un bersaglio (vivente, Costrutto o superficie) e vi innesti una carica. Per 3 turni puoi detonarla, una sola volta: danno = tier in 3 m dal punto d\'innesto. Se il bersaglio ha il tag Batteria, l\'esplosione è +1 tier.',
    { costCs: 3, hasDamage: true, durata: 'tre_turni' },
  ),
  makeActive(
    B,
    'kunou-baku-implosione-sofferenza',
    'Kunō-Baku (苦悩爆) — Implosione della Sofferenza',
    'Tutto il dolore inflitto, restituito in un solo lampo.',
    'Attiva · [Emanazione a distanza][Energetica] · Tier base 3 · CS 3 · 1/4. Scegli un bersaglio entro 8 m con almeno 3 stack di status, qualsiasi combinazione: rimuovi tutte le stack e le converti in un\'esplosione centrata sul bersaglio, danno = tier per stack rimossa, area 3 m.',
    { costCs: 3, hasDamage: true },
  ),
  makeActive(
    B,
    'toshi-investimento-energetico',
    'Tōshi (投資) — Investimento Energetico',
    "L'analista smette di spendere e comincia a versare. Ogni gesto, ogni colpo, lascia una parte di sé in un serbatoio che porta sotto la pelle: le venature di luce si moltiplicano, il respiro si fa corto, il corpo si gonfia di una pressione che non scarica — la trattiene, la conserva, la fa fruttare. Poi, in un solo istante scelto, riscuote tutto in un'unica onda nera.",
    "Attiva · [Nessuna][Potenziamento] · CS 2 (apertura) · 1/4 · grado richiesto: Sentatsu Bunsekikan [SB]. Apri un [Investimento] su di te. Per 3 turni, ogni quarto e a ogni lancio di waza puoi spostare CS dal tuo serbatoio nell'Investimento (riserva separata: non conta verso l'Overheat). In qualsiasi momento entro la durata puoi riscuotere rilasciando tutto l'Investimento insieme a una singola waza: questa ottiene +2 danno (piatto) e +1 m di gittata per ogni CS investito.\n\n↳ Se vieni reso incosciente, o passi un intero turno senza versare nell'Investimento, lo perdi.",
    { costCs: 2, costJigo: () => 4, durata: 'tre_turni', prereqGradoMin: 4 },
  ),
  makeActive(
    B,
    'shakkin-indebitamento',
    'Shakkin (借金) — Indebitamento',
    "L'analista posa il palmo sul bersaglio e gli inietta ciò che nessuno ha chiesto: un prestito forzato di Jigo-Ka nera che si annida nella carne e marchia la pelle del suo simbolo. Il debito non sta fermo — cresce a ogni alba, come ogni debito fa. L'unico modo per estinguerlo è restituirlo all'usuraio, colpo su colpo. Ma se l'analista decide di riscuotere, ciò che era stato prestato torna indietro tutto insieme, e l'interesse si paga in fuoco.",
    "Attiva · [Contatto] → [Emanazione a Distanza][Energetica] · CS 5 · 1/4 · grado richiesto: Kanteikan [K]. Colpisci un bersaglio a [Contatto] e gli imponi un [Debito] (status): inietti 2 stack iniziali. Per 3 turni:\n\n— Interessi: all'inizio di ogni tuo turno, il Debito cresce di +1 stack (max 6);\n\n— Restituzione: ogni volta che il bersaglio ti colpisce con una waza a [Contatto], il Debito cala di 1 stack.\n\nRiscossione (a comando, 1/4, oppure automatica alla scadenza): tutte le stack si convertono in un'esplosione [Energetico][Emanazione a Distanza] centrata sul bersaglio, raggio 3 m, danno = 5 per stack. Massimo un Debito per bersaglio. Se l'analista è reso incosciente, il Debito si dissolve.",
    { costCs: 5, costJigo: () => 10, hasDamage: true, durata: 'tre_turni', prereqGradoMin: 5 },
  ),
]
