/** Hensei-dō (変成道) — Parte III Oyasumi_Manuale_Completo.pdf + waza avanzate ROADMAP (19 waza). */
import type { WazaDef } from '../wazaPool'
import { makeActive, makePassive } from './waza-pool-builders'

const B = 'trasformazione' as const

export const HENSEI_WAZA_POOL: WazaDef[] = [
  makePassive(
    B,
    'ishi-volere',
    'Ishi (意志) — Volere',
    'Basta volerlo perché ciò che esce dalla mano cambi natura a metà volo.',
    'Passiva · CS 1 per uso. Cambi la Consistenza di una tua waza durante l\'esecuzione (non Nulla né Elementale). Se la waza è già Elementale, puoi cambiarne solo l\'elemento.',
    { costCs: 1 },
  ),
  makePassive(
    B,
    'kyosei-hen-mutazione-imposta',
    'Kyōsei-Hen (強制変) — Mutazione Imposta',
    'Il mondo intorno cede al tuo gesto: ciò che era duro si fa altro.',
    'Passiva · CS 1 per uso. Cambi la Consistenza di Costrutti entro 8 m (non Nulla né Elementale); la modifica dura 3 turni.',
    { costCs: 1 },
  ),
  makePassive(
    B,
    'genso-ka-elementalizzazione',
    'Genso-Ka (元素化) — Elementalizzazione',
    'Un tocco di volontà e la tecnica si veste del tuo elemento.',
    'Passiva · CS 1 per uso. Cambi la Consistenza di una tua waza in esecuzione in Elementale, elemento a scelta. Non applicabile a waza Nulla o già Elementali.',
    { costCs: 1 },
  ),
  makePassive(
    B,
    'renkin-soku-regole-alchemiche',
    'Renkin-Soku (錬金則) — Regole Alchemiche',
    'La legge dell\'oscillazione: nessuno stato due volte di fila.',
    'Passiva · CS 0, cuore di Yuragi. Non puoi usare due waza con la stessa Consistenza consecutivamente. Ogni cambio conferisce l\'effetto alchemico della nuova consistenza.',
  ),
  makePassive(
    B,
    'kenja-no-ishi-pietra-filosofale',
    'Kenja no Ishi (賢者の石) — Pietra Filosofale',
    'Il costrutto si comprime, vibra, si crepa — e sotto le crepe affiora un cristallo rosso sangue.',
    'Passiva · CS 1. Un tuo Costrutto Solido muta in 2 turni in un cristallo rosso sangue. Distrutto a contatto, concede +2 tier alla tua prossima waza.',
    { costCs: 1, durata: 'due_turni' },
  ),
  makePassive(
    B,
    'roei-scia-incontrollata',
    'Rōei (漏洩) — Scia Incontrollata',
    'Trasformare lascia residui: una scia del tuo elemento che avvelena il terreno.',
    'Passiva · CS 0. Quando cambi una tua waza Energetica in Elementale, lungo la sua gittata resta una scia gassosa dell\'elemento (stesse dimensioni della waza) per 2 turni. Chi finisce il turno o passa 2 quarti nella scia subisce +1 stack dello status.',
  ),
  makePassive(
    B,
    'hanno-reattivita-consistenza',
    'Hannō (反応) — Reazione di Consistenza',
    'Due nature che non dovrebbero toccarsi, e il campo reagisce.',
    'Passiva · CS 0. Quando una tua waza con Consistenza definita colpisce una zona di consistenza diversa (scia, zona, Costrutto), scatta la reazione corrispondente (Fuoco+Gassoso, Fulmine+Liquido, Acqua+Solido, Aria+Sonoro, Gravità+Energetico).',
  ),
  makeActive(
    B,
    'wana-trappola',
    'Wana (罠) — Trappola!',
    'Ciò che era già lì, all\'improvviso, è qualcos\'altro.',
    'Attiva · [Nessuna] · CS 1 · 1/4. Cambi la Consistenza di una tua tecnica già in campo da almeno 1 turno in quella di un Elemento. La modifica dura 1 turno.',
    { costCs: 1, durata: 'un_turno' },
  ),
  makeActive(
    B,
    'ihen-aberrazione',
    'Ihen (異変) — Aberrazione',
    "L'arto cede il posto all'arma: carne che diventa costrutto.",
    'Attiva · [Potenziamento][Nulla] · Tier base 2 · CS 2 · 1/4. Sostituisci un tuo arto con un Costrutto brandito come arma per 4 turni (danno = tier). Se il costrutto viene rotto, l\'arto resta inutilizzabile.',
    { costCs: 2, hasDamage: true, durata: 'quattro_turni' },
  ),
  makeActive(
    B,
    'bogai-disturbo',
    'Bōgai (妨害) — Disturbo',
    'La tua energia si fa ronzio e acceca i sensi altrui.',
    'Attiva · [Emanazione][Energetica] · CS 2 · 1/4. Rendi la tua Jigo-Ka un ronzio per 3 turni, propagato per 8 m: interferisce con la Jigo-Ka altrui, disturbando le abilità sensoriali basate su di essa. Finché ronzi, ogni tuo colpo a contatto riduce di 2 CS il bersaglio.',
    { costCs: 2, durata: 'tre_turni' },
  ),
  makeActive(
    B,
    'oboro-velo-onirico',
    'Oboro (朧) — Velo Onirico',
    'Un velo invisibile, e ciò che vi sta sotto smette di mostrarsi al mondo.',
    'Attiva · [Nessuna] · CS 2 · 1/4. Crei un velo invisibile di 4×8 m, posabile ovunque: nasconde le vere proprietà di ciò che copre completamente. Solo la tua Jigo-Ka può interagirvi. Permane 3 turni.',
    { costCs: 2, durata: 'tre_turni' },
  ),
  makeActive(
    B,
    'bocho-espansione-instabile',
    'Bōchō (膨張) — Espansione Instabile',
    'Cresce oltre il suo limite, e per questo si spezza.',
    'Attiva · [Nessuna] · CS 1 · 1/4. Un Costrutto entro 8 m sale di una taglia per 1 turno, poi si rompe.',
    { costCs: 1, durata: 'un_turno' },
  ),
  makeActive(
    B,
    'kokan-scambio-consistenza',
    'Kōkan (交換) — Scambio di Consistenza',
    'Il muro diventa nebbia, la nebbia diventa muro.',
    'Attiva · [Nessuna] · CS 2 · 1/4. Due oggetti o Costrutti entro 8 m si scambiano la Consistenza per 3 turni (es. muro Solido ↔ nube Gassosa). Richiede consistenze definite; non applicabile a costrutti impugnati da terzi.',
    { costCs: 2, durata: 'tre_turni' },
  ),
  makeActive(
    B,
    'sokotsu-fusione-instabile',
    'Sōkotsu (相崩) — Fusione Instabile',
    'Due stati in un istante, e lo stress li fa esplodere.',
    'Attiva · [Emanazione a distanza] · Tier base 3 · CS 3 · 1/4. Forzi un Costrutto entro 8 m a oscillare rapidamente tra due stati (es. Solido→Gassoso→Solido): lo stress lo fa esplodere in un\'area di 3 m, danno = tier a ogni bersaglio. I frammenti hanno la consistenza finale della transizione.',
    { costCs: 3, hasDamage: true },
  ),
  makeActive(
    B,
    'shoku-corrosione',
    'Shoku (蝕) — Corrosione',
    'Lenta, inesorabile: la materia si arrende al tuo elemento.',
    'Attiva · [Contatto] · CS 2 · 1/4. Tocchi un Costrutto o uno Scudo e ne forzi gradualmente la Consistenza verso Elementale: per 3 turni perde 1 tier di Resistenza a turno, poi diventa Elementale col tuo elemento. Se distrutto durante la transizione, rilascia lo status in 3 m.',
    { costCs: 2, hasDamage: true, durata: 'tre_turni' },
  ),
  makeActive(
    B,
    'tenka-dalla-padella-alla-brace',
    'Tenka (転化) — Dalla Padella alla Brace',
    'Lo stesso male, un volto nuovo.',
    'Attiva · [Nessuna][Contatto] · CS 1 · 1/4. Tocchi un bersaglio con almeno 1 stack di status elementale e ne trasmuti la natura: lo status scelto diventa un altro status a tua scelta, con lo stesso numero di stack.',
    { costCs: 1 },
  ),
  makeActive(
    B,
    'shokubai-catalisi',
    'Shokubai (触媒) — Catalisi',
    'Ogni mutazione, da ora, lascia il segno.',
    'Attiva · [Nessuna][Potenziamento] · CS 2 · 1/4. Per 3 turni, ogni volta che cambi la Consistenza di una tua waza in esecuzione (via Ishi, Genso-Ka, ecc.), la waza applica automaticamente +1 stack dello status della nuova consistenza.',
    { costCs: 2, durata: 'tre_turni' },
  ),
  makeActive(
    B,
    'nagori-principio-instabilita',
    'Nagori (名残) — Principio di Instabilità',
    "L'analista non lascia mai del tutto uno stato: ogni forma che abbandona resta aggrappata alla successiva come un'ombra che il corpo non ha finito di scrollarsi di dosso. La waza si smantella e si ricostruisce, imperfetta, attraversata da tensioni visibili — e nel passaggio trascina con sé un residuo di ciò che era un istante prima, il respiro doppio di Retsuja, ciò che è e ciò che ha appena smesso di essere.",
    "Attiva · [Nessuna][Potenziamento] · CS 3 · 1/4 · grado richiesto: Sentatsu Bunsekikan [SB]. Attivi il Principio di Instabilità su di te. Per 3 turni, ogni volta che cambi la [Consistenza] di una tua waza, questa guadagna un effetto collaterale basato sulla consistenza di partenza (quella che abbandoni) — in aggiunta all'effetto alchemico Yuragi della consistenza in arrivo:\n\n— [Solido] → +1 tier di danno\n\n— [Liquido] → +4 m di gittata\n\n— [Gassoso] → +1 turno di permanenza (se ha durata)\n\n— [Sonoro] → ignora 1 tier di Resistenza e di [Scudi]\n\n— [Elementale] → applica +1 stack dello status elementale abbandonato\n\n— [Energetico] → la waza ottiene priorità (vince gli scambi in parità d'Indice)",
    { costCs: 3, costJigo: () => 6, durata: 'tre_turni', prereqGradoMin: 4 },
  ),
  makeActive(
    B,
    'igyo-rensei-insegnamenti-tucker',
    'Igyō-Rensei (異形錬成) — Insegnamenti di Tucker',
    "L'analista posa la mano su una forma e la costringe a tradire sé stessa. Non un cambio docile: una trasmutazione aberrante, dove il costrutto si smantella con violenza e si ricompone nel nuovo stato portando il marchio di chi l'ha rifatto. Ciò che era saldo si liquefà e cola, ciò che aveva forma si disperde in nube, ciò che taceva esplode. È l'alchimia che non ripara: deforma.",
    "Attiva · [Contatto] · CS 5 · 1/4 · grado richiesto: Kanteikan [K]. Tocchi un [Costrutto] o [Scudo] (tuo o nemico) e ne forzi la [Consistenza]: il bersaglio assume istantaneamente quella consistenza con tutte le proprietà associate. La transizione è violenta e produce un effetto diverso secondo la trasformazione:\n\n— → [Solido]: +2 tier di Resistenza, ma diventa [Immobile] (non spostabile da Telecinesi/Furia — Ayatsuri, Hajiki, Hikiyose) per 1 turno.\n\n— → [Liquido]: perde metà Resistenza e si espande, coprendo una zona [Liquido] a terra di raggio 4 m.\n\n— → [Gassoso]: perde forma e si disperde in una nube di raggio 4 m per 2 turni.\n\n— → [Elementale]: esplode in raggio 4 m applicando lo status elementale affine dell'analista (2 stack) a ogni bersaglio nell'area; il costrutto/scudo originale è distrutto.",
    { costCs: 5, costJigo: () => 10, hasDamage: true, prereqGradoMin: 5 },
  ),
]
