/** Itō-dō (糸道) — Parte III Oyasumi_Manuale_Completo.pdf + waza avanzate ROADMAP (19 waza). */
import type { WazaDef } from '../wazaPool'
import { makeActive, makePassive } from './waza-pool-builders'

const B = 'manipolazione' as const

export const ITO_WAZA_POOL: WazaDef[] = [
  makePassive(
    B,
    'ayatsuri-filo-burattinaio',
    'Ayatsuri (操り) — Filo del Burattinaio',
    "L'analista tende un filo invisibile e ciò che tocca smette di appartenere alla terra: diventa Kugutsu, marionetta sospesa al suo volere.",
    'Passiva · CS 0, genera 1 Tensione finché attiva. Sollevi un Costrutto fino a taglia Media, controllandolo vagamente; puoi muoverlo o scagliarlo. Parametri di movimento = il tuo Movimento (Undō) per taglia Piccola, ×0,75 per Media.',
  ),
  makePassive(
    B,
    'someito-filo-tinto',
    'Someito (染め糸) — Filo Tinto',
    "Il filo si intinge della natura che l'analista sceglie, e la marionetta cambia sostanza lungo la corda.",
    'Passiva · CS 0. Cambi liberamente la Consistenza dei Costrutti che hai generato.',
  ),
  makePassive(
    B,
    'yugami-filo-deforme',
    'Yugami (歪み) — Filo Deforme',
    "Un gesto delle dita e la forma cede: la waza si comprime o si dilata in silenzio, mentre per un battito la Jigo-Ka dell'analista resta immobile.",
    'Passiva · CS 0. Cambi la Categoria di una tua waza durante l\'esecuzione: Emanazione o Propagazione ↔ Propagazione Conica. Gittata ×1,5 nel primo caso, ×0,5 nel secondo. L\'origine diventa l\'analista.',
  ),
  makePassive(
    B,
    'tazuna-redini',
    'Tazuna (手綱) — Redini',
    "Il colpo non è mai libero: corre lungo redini che solo l'analista impugna. Può piegarlo a metà volo, o richiamarlo all'impatto perché prosegua altrove.",
    'Passiva · CS 0 (modalità Rimbalzo: +1 CS opzionale). Guida: cambi la direzione di una tua waza Raggio o Proiettile fino a 180° durante l\'esecuzione. Rimbalzo: se la waza impatta prima di consumare la gittata, può rimbalzare nella direzione scelta e proseguire per i metri rimasti — vale anche per le waza Sonore ad area, con rimbalzo fino a 6 m; +1 CS per allungare il rimbalzo di 4 m.',
  ),
  makePassive(
    B,
    'wakeito-filo-sdoppiato',
    'Wakeito (分け糸) — Filo Sdoppiato',
    'Un filo che si biforca: la stessa volontà, due capi, due destini.',
    'Passiva · CS 0. Una tua waza Raggio può dividersi in due diramazioni verso bersagli diversi (danno ×0,75 ciascuna); una tua waza Proiettile può raddoppiare di numero (danno ×0,75, stessa direzione).',
  ),
  makePassive(
    B,
    'hikitome-trattenuta',
    'Hikitome (引き止め) — Trattenuta',
    '"Un colpo non viene fermato: viene trattenuto." Il proiettile resta sospeso al filo, in attesa.',
    'Passiva · CS 1, genera 1 Tensione mentre è sospesa. "Congeli" una tua waza Proiettile in un punto entro la sua gittata: resta sospesa 1 turno, poi riparte nella stessa direzione senza ulteriore costo. Il turno di sospensione conta come un rilancio.',
    { costCs: 1 },
  ),
  makeActive(
    B,
    'hajiki-fionda-filo',
    'Hajiki (弾き) — Fionda del Filo',
    'Il filo si tende fino al limite, poi lascia: la marionetta vola via come una pietra dalla fionda.',
    'Attiva · [Proiettile][Solido] · Tier base 2 · CS 2 · 1/4. Scagli in linea retta un Costrutto Solido che stai sollevando con Ayatsuri, per 12 m; danno = tier.',
    { costCs: 2, hasDamage: true },
  ),
  makeActive(
    B,
    'irekae-scambio-fili',
    'Irekae (入れ替え) — Scambio dei Fili',
    'Due marionette, due fili incrociati: ciò che era qui è là, e viceversa.',
    'Attiva · [Nessuna] · CS 1 · 1/4. Due tuoi Costrutti Solidi entro 8 m invertono posizione, mantenendo le loro proprietà — un costrutto in volo prosegue la traiettoria dalla nuova posizione.',
    { costCs: 1 },
  ),
  makeActive(
    B,
    'mayu-wari-bozzolo-squarciato',
    'Mayu-Wari (繭割り) — Bozzolo Squarciato',
    'Il bozzolo di filo si lacera dall\'interno e sputa schegge guidate.',
    'Attiva · [Proiettile][Solido] · Tier base 2 · CS 2 · 1/4. Un tuo Costrutto Solido entro 8 m implode generando 4 Proiettili Solidi diretti a un bersaglio; danno = tier, ripartito tra le schegge che colpiscono.',
    { costCs: 2, hasDamage: true },
  ),
  makeActive(
    B,
    'hikiyose-richiamo-fili',
    'Hikiyose (引き寄せ) — Richiamo dei Fili',
    'Fili di carica opposta: ciò che respinge e ciò che attrae, intrecciati.',
    'Attiva · [Nessuna] · CS 2 · 1/4, genera 1 Tensione. Rendi un tuo Costrutto Solido entro 8 m Positivo per 2 turni; fino a 2 altri entro 8 m diventano Negativi (+1 CS per crearne di nuovi già Negativi). Ogni Solido Negativo viene attratto con forza verso il Positivo.',
    { costCs: 2, durata: 'due_turni' },
  ),
  makeActive(
    B,
    'musubi-nodo-gemello',
    'Musubi (結び) — Nodo Gemello',
    'Due marionette annodate allo stesso filo: feriscine una, sanguina l\'altra.',
    'Attiva · [Nessuna] · CS 2 · 1/4, genera 1 Tensione. Leghi due Costrutti Solidi entro 8 m: per 4 turni, ciò che accade a uno si ripete sull\'altro.',
    { costCs: 2, durata: 'quattro_turni' },
  ),
  makeActive(
    B,
    'mayakashi-inganno-filo',
    'Mayakashi (まやかし) — Inganno del Filo',
    'Il filo veste la marionetta di un\'altra pelle.',
    'Attiva · [Nessuna] · CS 1 · 1/4. Fai apparire un tuo Costrutto come un altro Costrutto che vedi o un oggetto del tuo inventario, per 4 turni. Sotto i 4 m la vera forma è visibile.',
    { costCs: 1, durata: 'quattro_turni' },
  ),
  makeActive(
    B,
    'ubaiito-filo-rubato',
    'Ubaiito (奪い糸) — Filo Rubato',
    "L'analista afferra il filo altrui e lo strappa di mano al suo padrone.",
    'Attiva · [Nessuna] · CS 2 · 1/4. Tenti di strappare il controllo di un Costrutto nemico entro 8 m: confronto d\'Indice (Skiru mentali, es. Fudōshin o Kansatsu) contro l\'Indice del creatore. Se prevali, il controllo passa a te per 2 turni; il creatore può ritentare lo strappo. Solo su costrutti di taglia Media o inferiore.',
    { costCs: 2, durata: 'due_turni' },
  ),
  makeActive(
    B,
    'unari-ronzio-filo',
    'Unari (唸り) — Ronzio del Filo',
    'Il filo teso non tace: vibra di una nota bassa che fa girare la testa a chi gli sta vicino.',
    'Attiva · [Emanazione][Sonoro] · CS 2 · 1/4, genera 1 Tensione. Permei un tuo Costrutto entro 8 m di un\'onda sonora costante: per 3 turni emette un ronzio in un\'area di 4 m. Chi inizia il turno nell\'area subisce lo status Vertigini.',
    { costCs: 2, hasDamage: true, durata: 'tre_turni' },
  ),
  makeActive(
    B,
    'shime-stretta-filo',
    'Shime (締め) — Stretta del Filo',
    'Il filo si avvolge e cinge, finché la marionetta si fa più piccola, più dura, più letale.',
    'Attiva · [Nessuna] · CS 1 · 1/4. Comprimi un tuo Costrutto Solido entro 8 m, riducendone la taglia di un livello (Grande→Media, Media→Piccola). Guadagna +1 tier di Resistenza, e +1 tier di danno se usato come Proiettile. Permanente.',
    { costCs: 1 },
  ),
  makeActive(
    B,
    'rensa-catena-fili',
    'Rensa (連鎖) — Catena di Fili',
    'Due gesti, un\'unica catena: quando il primo filo si spegne, il secondo è già teso.',
    'Attiva · [Nessuna] · CS = somma delle due waza · 1/4. Carichi due waza e ne paghi entrambi i costi, scegliendo l\'ordine. Quando la prima finisce, la seconda si attiva automaticamente dal punto in cui era la prima. Entrambe nello stesso turno.',
    { costCs: 0 },
  ),
  makeActive(
    B,
    'kankatsu-giurisdizione',
    'Kankatsu (管轄) — Giurisdizione',
    "L'analista tende un filo e lo pianta nell'aria attorno a sé, tracciando un cerchio invisibile di cui si dichiara padrone. Ogni colpo nemico che varca quel confine viene afferrato a metà volo da capi di filo che lo intingono del colore della sua Jigo-Ka: per un istante la corda di Retsuja lo trattiene, poi la mano che lo guida non è più quella che l'ha lanciato.",
    "Attiva · [Nessuna][Potenziamento] · CS 4 · 1/4 · grado richiesto: Sentatsu Bunsekikan [SB]. Dichiari Giurisdizione su una [Categoria] a scelta tra [Proiettile] e [Raggio]. Per 3 turni, una volta per turno, quando una waza nemica di quella Categoria entra entro 8 m da te, puoi spendere +2 CS per reclamarla: dall'istante in cui entra nel cerchio è considerata come appena lanciata da te. Bersaglio e gittata restano gli originali, ma ora la waza è tua — le tue passive Itō possono agire su di essa (redini, sdoppiamento, consistenza, trattenuta…) e le tue passive di consistenza/danno la leggono come propria.\n\n↳ Ogni waza reclamata che stai manipolando genera 1 Tensione finché la tieni.",
    { costCs: 4, costJigo: () => 8, durata: 'tre_turni', prereqGradoMin: 4 },
  ),
  makeActive(
    B,
    'chokurei-decreto',
    'Chokurei (勅令) — Decreto',
    "L'analista non muove più la marionetta: muove la legge che la regge. Un filo di luce scrive nell'aria un'unica sentenza, breve come un nodo, e il campo è costretto a obbedirle — perché ogni cosa, anche la più libera, era già legata al filo del destino di Meiju.",
    "Attiva · [Nessuna] · CS 6 · 1/4 · grado richiesto: Kanteikan [K]. Imponi un singolo Decreto, un comando che viola le regole naturali del combattimento. Si applica a un evento specifico, in corso o che avverrà entro 2 turni, in una gittata di 12 m. Un solo Decreto per turno.\n\nIl Decreto non può: cambiare [Consistenze], creare materia, potenziare un corpo, far esplodere energia. Può solo agire su movimento, direzione, posizione, [Categoria]. Esempi:\n\n— «Quella [Proiettile] torna al mittente.» → la waza inverte la direzione.\n\n— «Quei due [Costrutti] si scambiano di posto.» → scambio istantaneo (come Irekae, forzato).\n\n— «Quella waza si ferma.» → si congela sul posto; riparte al tuo prossimo turno sulla stessa traiettoria (come Hikitome, forzata su waza nemica).\n\n— «Quel bersaglio non può muoversi in quella direzione.» → un bersaglio entro gittata ha quella direzione di movimento negata per il turno.",
    { costCs: 6, costJigo: () => 12, prereqGradoMin: 5 },
  ),
  makeActive(
    B,
    'mugen-shihai-dominazione-onirica',
    'Mugen-Shihai (夢幻支配) — Dominazione Onirica',
    "L'analista pianta i piedi e apre tutti i fili insieme: una cupola sottile di corde si stende sopra il campo, e ogni cosa che vive là sotto sente un peso impercettibile sulle spalle. Non muove più le marionette a una a una — è il centro a cui tutti i fili tornano. Finché regge il cerchio, dentro di esso non accade nulla che la sua mano non senta, e quasi nulla che non possa reclamare. Ma chi tiene mille fili non può camminare.",
    "Attiva · [Emanazione][Nessuna] · CS 8 + mantenimento · 1/4 · grado richiesto: Shin'enkan [S]. Estendi il tuo dominio in un cerchio di raggio 10 m centrato su di te, per 4 turni (o fino a rottura). Entro la zona:\n\n— ogni [Costrutto] presente conta te come co-proprietario (puoi manipolarlo come tuo, senza strapparne la proprietà al creatore);\n\n— hai piena coscienza di ogni waza generata nella zona o che la attraversa;\n\n— al costo di 1/4, tratti 1 waza (qualsiasi Categoria, tua o altrui) come appena generata da te; gittata e direzione iniziali restano gli originali. Nessun limite di una-per-turno: sei limitato solo dai quarti.\n\nVincolo del centro: per mantenere la Dominazione puoi muoverti al massimo di metà Movimento a turno. Se percorri più metri (per scelta o forzato) o subisci più di 12 danno (tier 3) da un singolo colpo, la Dominazione si spezza e decade.\n\n↳ Ogni waza che reclami nella zona genera 1 Tensione (la cupola è un'unica ragnatela: più tiri, più vicino al Cedimento).",
    { costCs: 8, costJigo: () => 16, costJigoTipo: 'mantenimento', durata: 'quattro_turni', prereqGradoMin: 6 },
  ),
]
