/** Naikan-dō (内観道) — Parte III Oyasumi_Manuale_Completo.pdf + waza avanzate ROADMAP (17 waza). */
import type { WazaDef } from '../wazaPool'
import { makeActive, makePassive } from './waza-pool-builders'

const B = 'supporto' as const

export const NAIKAN_WAZA_POOL: WazaDef[] = [
  makePassive(
    B,
    'junno-pelle-apprende',
    'Junnō (順応) — Pelle che Apprende',
    'La Jigo-Ka risale sotto la pelle e si raccoglie nelle venature del punto d\'impatto, brillante come brace appena spenta. La carne ha imparato una sola lezione, e la dimentica appena gliene insegnano un\'altra.',
    'Passiva · CS 0. Quando subisci danno da una waza di una data Consistenza, fino al prossimo colpo di consistenza diversa la tua Resistenza verso quella consistenza aumenta di un valore pari al tier del colpo subìto. La nuova consistenza sovrascrive la precedente.',
  ),
  makePassive(
    B,
    'hibiki-gaeshi-eco-risposta',
    'Hibiki-Gaeshi (響き返し) — Eco di Risposta',
    "Una parte della Jigo-Ka non si dissolve: resta sotto la pelle come l'eco di una campana, e si unirà con la prima nota simile rilasciata dall'analista.",
    'Passiva · CS 0. Finché l\'ultima waza subìta ha una data Consistenza, ogni tua waza della medesima consistenza ottiene danno extra pari al tier del colpo subìto. Cambia automaticamente quando subisci una consistenza diversa.',
  ),
  makePassive(
    B,
    'jiga-hoki-ego-traboccante',
    'Jiga-Hōki (自我放棄) — Ego Traboccante',
    'Quando uno status morde la pelle, la Jigo-Ka si muove con più forza nei nodi; l\'arma, sotto la mano, diventa carne della sua carne.',
    'Passiva · CS 0. Mentre sei sotto almeno uno status, ogni tuo Potenziamento dura +1 turno. L\'arma impugnata conta come tuo Costrutto. Puoi trasferire un tuo Potenziamento a un Costrutto (massimo 1) finché lo tocchi; al distacco, permane sul costrutto fino a fine turno.',
  ),
  makePassive(
    B,
    'ittai-un-solo-corpo',
    'Ittai (一体) — Un Solo Corpo',
    "Il corpo non respinge l'effetto negativo: lo accoglie, lo diluisce nei nodi finché smette di essere distinguibile dal resto.",
    'Passiva · CS 0. Ogni Depotenziamento (malus di Skiru) su di te dura −1 turno. L\'arma conta come tuo Costrutto. Mentre sei depotenziato, puoi estendere il malus a un Costrutto avversario (massimo 1) finché lo tocchi; poi permane fino a fine tuo turno. Tu mantieni comunque il tuo malus.',
  ),
  makePassive(
    B,
    'naka-kae-scambio-nucleo',
    'Naka-Kae (中替え) — Scambio del Nucleo',
    'La Jigo-Ka può essere trascinata da una camera all\'altra prima che si saldi, ma brucia qualcosa di sé nel transito.',
    'Passiva · CS 0. Durante una tua waza Potenziamento, puoi sostituire una Skiru potenziata con un\'altra a scelta. La durata del Potenziamento si riduce di 2 turni.',
  ),
  makePassive(
    B,
    'tobi-kake-slancio-carica',
    'Tobi-Kake (飛び駆け) — Slancio in Carica',
    'La Jigo-Ka delle gambe risale e si accumula nelle spalle, in attesa che lo slancio venga riversato. Al primo contatto, tutta la carica si scarica.',
    'Passiva · CS 0. Se hai percorso almeno il doppio del tuo Movimento in metri nel turno prima di colpire, la tua prossima waza a Contatto del turno guadagna +1 tier di danno. Una volta per turno; decade a fine turno.',
  ),
  makeActive(
    B,
    'datsui-tate-scudo-spogliato',
    'Datsui-Tate (脱衣盾) — Lo Scudo Spogliato',
    "L'analista si spoglia di tutto ciò che si era costruito addosso e lo proietta appena oltre la pelle, come un samurai depone l'armatura davanti a un altare.",
    'Attiva · [Scudo][Energetico] · CS 2 · 1 turno. Rimuovi tutti i tuoi Potenziamento attivi e generi uno Scudo con Resistenza pari alla somma dei Bun sacrificati. Dura fino a fine prossimo turno o a esaurimento. Il turno seguente non puoi ricevere Potenziamento da alcuna fonte.',
    { costCs: 2, durata: 'un_turno' },
  ),
  makeActive(
    B,
    'datsui-yumi-arco-spogliato',
    'Datsui-Yumi (脱衣弓) — L\'Arco Spogliato',
    "Invece di una freccia, l'analista incocca la propria armatura: la Jigo-Ka compressa diventa un dardo che fende l'aria col peso intero della forza appena rinunciata.",
    'Attiva · [Proiettile][Energetico] · CS 2 · istantanea. Lanciabile solo con almeno 1 Potenziamento attivo. Rimuovi tutti i Potenziamento e generi un proiettile per 15 m; danno = somma dei Bun sacrificati. Il turno seguente non puoi ricevere Potenziamento.',
    { costCs: 2, hasDamage: true },
  ),
  makeActive(
    B,
    'hari-tsume-carico-trattenuto',
    'Hari-Tsume (張り詰め) — Carico Trattenuto',
    "L'analista spinge la Jigo-Ka contro l'osso come acqua forzata in un tubo già pieno. L'arto diventa una molla in attesa del rilascio.",
    'Attiva · [Nessuna][Potenziamento] · CS 2 · 2 turni. Scegli un arto. Il prossimo colpo a Contatto con quell\'arto ottiene Potenziamento +3, ripartito su Binshō e Kairyoku (Indice e danno del colpo). Finché attiva, l\'arto non può fare altro. Decade allo scarico o a fine durata.',
    { costCs: 2, durata: 'due_turni' },
  ),
  makeActive(
    B,
    'seni-gake-avvolgimento-fibre',
    'Sen\'i-Gake (繊維掛け) — Avvolgimento delle Fibre',
    'La Jigo-Ka scende lungo le fibre e le rinforza, avvolgendole come filo intorno a un\'anima di legno; il resto del corpo perde lucentezza.',
    'Attiva · [Nessuna][Potenziamento] · CS 2 · 2 turni. Scegli un settore (Gambe, Braccia o Torace) e un tipo di fibra. Per 2 turni, il Potenziamento si applica solo alle azioni di quel settore: Fibre Bianche → +2 Kairyoku; Fibre Neuromuscolari → +2 Binshō; Fibre Rosse → +2 Nintai.',
    { costCs: 2, durata: 'due_turni' },
  ),
  makeActive(
    B,
    'geki-ryu-corrente-violenta',
    'Geki-Ryū (激流) — Corrente Violenta',
    "L'analista apre tutti i nodi e lascia che la Jigo-Ka li attraversi a una velocità non concepita per essere sostenuta. Poi le camere svuotate restano vuote.",
    'Attiva · [Nessuna][Potenziamento] · CS 2 · 2 + 2 turni. Per 2 turni, +3 Binshō. Allo scadere, contraccolpo di −3 Binshō per altri 2 turni.',
    { costCs: 2, durata: 'due_turni' },
  ),
  makeActive(
    B,
    'hada-yuzuri-cessione-pelle',
    'Hada-Yuzuri (肌譲り) — Cessione attraverso la Pelle',
    "L'analista apre i nodi verso l'esterno non per emettere ma per cedere: lo status trova un nuovo contenitore nella carne avversaria.",
    'Attiva · [Nessuna][Potenziamento] · CS 2 · istantanea. Colpendo un vivente a Contatto, scegli uno status attivo su di te e lo trasferisci al bersaglio (stessi stack, durata residua); viene rimosso da te.',
    { costCs: 2 },
  ),
  makeActive(
    B,
    'tsubo-uchi-colpo-punto',
    'Tsubo-Uchi (壺打ち) — Colpo al Punto',
    "L'analista deposita la Jigo-Ka in un singolo punto come un sigillo a freddo; ogni colpo che torna lì pesa più del precedente.",
    'Attiva · [Nessuna][Contatto] · CS 1 · persistente, decade dopo 2 turni. Colpisci e marchi una zona (Testa, Braccia, Busto o Gambe) con un Punto di Pressione. Ogni tuo colpo successivo sulla stessa zona infligge danno extra crescente: +2, poi +4, poi +6 (cap +6). Decade se la zona non viene colpita per 2 turni. Massimo 1 punto per bersaglio; cambiare zona resetta il contatore.',
    { costCs: 1, hasDamage: true },
  ),
  makeActive(
    B,
    'shoka-sublimazione',
    'Shōka (昇華) — Sublimazione',
    "L'analista riconosce lo status che lo affligge non come ferita ma come materiale grezzo, e lo lavora dentro di sé: il dolore diviene forza, la sofferenza testardaggine.",
    'Attiva · [Nessuna][Potenziamento] · CS 2 · persistente finché resta almeno 1 stack. Lanciabile con almeno 2 stack di uno status negativo. Consumi 1 stack; finché ne resta almeno 1, le tue waza Potenziamento ricevono un boost extra che supera la Capacità di Junkan — il dolore è carburante: Incendiato → +2 Kairyoku · Sovraccarico → +2 Binshō · Torpore → +2 Nintai · Appesantimento → +2 Seishin Tanren · Vertigini → +2 Shakai Kaikyū. Quando un Potenziamento così alimentato decade, consuma anche 1 stack residua.',
    { costCs: 2, durata: 'mantenimento' },
  ),
  makeActive(
    B,
    'shokushin-lettura-corpo',
    'Shokushin (触診) — Lettura del Corpo',
    "L'analista non colpisce per ferire: colpisce per leggere. Nel punto di contatto la sua Jigo-Ka risale sotto la pelle del bersaglio come una mano che tasta un meccanismo al buio, e per un istante sente dove il corpo è pieno e dove è vuoto, dove la forza si accumula e dove il flusso s'inceppa. È l'introspezione della Via rivolta verso un altro — l'occhio interno che si apre nella carne di chi gli sta davanti.",
    "Attiva · [Nessuna][Contatto] · CS 3 · 1/4 · grado richiesto: Sentatsu Bunsekikan [SB]. Colpisci un bersaglio a [Contatto] e ne leggi il corpo. Ottieni:\n\n— la Skiru più alta e la più bassa;\n\n— se ha [Potenziamenti] attivi e su quale Skiru;\n\n— quali Status possiede;\n\n— una stima sommaria della Jigo-Ka (CS) residua;\n\n— gli Stili di appartenenza e alcune passive (non tutte — quante, lo decide il fato/master).\n\nUn solo bersaglio letto alla volta: leggerne un altro sovrascrive. Il tuo prossimo colpo contro il bersaglio letto infligge +1 tier di danno; il prossimo colpo che subisci da lui approfondisce la Lettura (rivela una passiva in più).",
    { costCs: 3, costJigo: () => 5, hasDamage: false, prereqGradoMin: 4 },
  ),
  makeActive(
    B,
    'komei-chi-lo-ha-deciso',
    'Kōmei (抗命) — Chi lo ha Deciso?',
    "L'analista guarda ciò che lo affligge e si rifiuta di subirlo. La Jigo-Ka inverte la corrente nei nodi: il fuoco che lo bruciava ora gli riveste i pugni, il peso che lo inchiodava diventa slancio, le vertigini si fanno furia. Il dolore non viene sopportato e nemmeno solo bruciato come carburante — viene ribaltato, costretto a lavorare per chi avrebbe dovuto piegare.",
    "Attiva · [Nessuna][Potenziamento] · CS 6 · 1/4 · grado richiesto: Kanteikan [K]. Lanciabile solo se hai almeno uno Status negativo attivo. Rimuovi immediatamente tutti i tuoi Status negativi: ognuno si converte nel suo opposto per 3 turni (atto singolo, non mantenimento):\n\n— [Incendiato] / [Emorragia] → il corpo si fa rovente: ogni tuo colpo a [Contatto] applica [Incendiato] (1 stack).\n\n— [Sovraccarico] → l'eccesso diventa carburante: +2 CS rigenerati per turno.\n\n— [Torpore] → la rigidità diventa armatura: +10% mitigazione.\n\n— [Appesantimento] → il peso diventa potenza: i colpi a [Contatto] infliggono +1 tier di danno.\n\n— [Vertigini] → l'instabilità diventa ferocia: ottieni 2 stack di [Ira].",
    { costCs: 6, costJigo: () => 12, durata: 'tre_turni', prereqGradoMin: 5 },
  ),
  makeActive(
    B,
    'hogo-sutura-ego',
    'Hōgō (縫合) — Sutura dell\'Ego',
    "L'analista, che ha imparato a ricucire i propri flussi mentre combatte, posa la mano sul nemico e fa l'opposto: infila la propria Jigo-Ka estranea nei suoi percorsi e li cuce chiusi. Il bersaglio sente un filo che non è suo bloccare ciò che prima scorreva — un punto di sutura nell'Ego, che terrà finché non avrà la forza di strapparlo via.",
    "Attiva · [Nessuna][Contatto] · CS 7 · 1/4 · grado richiesto: Shin'enkan [S]. Colpisci un bersaglio a [Contatto] e applichi una Sutura a scelta (max una per bersaglio), per 3 turni:\n\n— Sutura Offensiva: sigilli la Skiru più alta del bersaglio: −3 a quella Skiru (riduce Indice e danno delle azioni che la usano). Non può essere potenziata; se lo era, perde il [Potenziamento] e non può acquisirne per la durata.\n\n— Sutura di Stile: sigilli una passiva del bersaglio (a tua scelta fra quelle rivelate dalla Lettura): non può usarla per la durata.\n\n— Sutura Elementale: congeli tutti gli Status attivi sul bersaglio: non possono essere rimossi né decadere, restano bloccati al livello di stack attuale.\n\nRottura: il bersaglio può spezzare la Sutura spendendo 4 CS e dedicando 1 Quarto intero alla purificazione. Finché non lo fa, l'effetto persiste.",
    { costCs: 7, costJigo: () => 14, hasDamage: false, durata: 'tre_turni', prereqGradoMin: 6 },
  ),
]
