/**
 * Rami Waza (le "Vie") — etichette e descrizioni UI.
 * Modificabile dal tester: Idee → Categorie Waza → Salva su disco.
 */

export type WazaBranch =
  | 'proiezione'
  | 'manipolazione'
  | 'materializzazione'
  | 'emissione'
  | 'trasformazione'
  | 'supporto'
  | 'generiche'
  | 'ordine'
  | 'onimori'

export const BRANCH_LABELS: Record<WazaBranch, string> = {
  proiezione: 'Tōka-dō: Via della Lanterna',
  manipolazione: 'Ito-Dō: Via del Filo',
  materializzazione: 'Genzai-Dō: Via del Sigillo',
  emissione: 'Hō-Dō: Via del Collasso',
  trasformazione: 'Hensei-Dō: Via della Deformazione',
  supporto: 'Naikan-Do (Supporto)',
  generiche: 'Generiche',
  ordine: 'Ordine · Arsenale militare',
  onimori: 'Oni no Mori',
}

export const BRANCH_DESCRIPTIONS: Partial<Record<WazaBranch, string>> = {
  proiezione: "Chi intraprende il Tōka-dō, si vedrà abile in waza di proiezione: la via infatti incanala ed infonde Jigoka attraverso l'ausilio di armi ed oggetti, potenziandone la resa. Si dice che chi intraprende la Via della Lanterna sia già un abile combattente — e che attraverso la propria arma si lasci guidare nella battaglia. È per questo che l'oggetto designato, o gli oggetti, prendono il nome di Tōrō (lanterna).",
  manipolazione: "Si dice che nulla, al mondo, sia davvero libero. Ogni cosa è legata a un’altra, anche quando sembra muoversi da sola. Chi percorre l’Itō-dō impara a vedere ciò che gli altri ignorano: non gli oggetti, ma i legami che li attraversano. Fili sottili, invisibili, che uniscono movimento a conseguenza, gesto a destino.\nNon vengono creati. Sono già lì.\n\nL’analista non impone la propria volontà sul mondo—la inserisce tra le tensioni già esistenti, imparando a tirare, allentare, deviare. Un colpo non viene fermato: viene trattenuto. Una traiettoria non viene cambiata: viene guidata. Un oggetto non viene mosso: viene richiamato lungo un filo che già lo lega.\n\nMa ogni filo, per quanto sottile, esercita una pressione. E più il campo si riempie, più la tensione cresce.\n\nChi percorre questa Via vive in equilibrio costante tra controllo e cedimento. Perché i fili non spezzano solo ciò che tengono— a volte, si spezzano nelle mani di chi li tira.",
  materializzazione: "Chi percorre questa Via non crea dal nulla, né richiama ciò che esiste altrove. Scrive. La Jigo-ka viene tracciata nello spazio sotto forma di sigilli, simboli e formule che non brillano finché non vengono completate, e nel momento in cui lo sono, la realtà è costretta ad adeguarsi. Un [Costrutto] non nasce: viene dichiarato esistente, vincolato da un ordine che lo obbliga a mantenere forma e funzione finché il sigillo regge. Ogni creazione è una frase incompleta che si sostiene sulla volontà dell’analista, e più è complessa più richiede precisione, memoria e controllo. Il corpo stesso può diventare superficie di scrittura, inciso da segni che sostituiscono carne con struttura, trasformando ciò che è fragile in qualcosa di imposto. Ma ogni sigillo è un vincolo, e ogni vincolo può cedere: quando la scrittura si incrina, ciò che esisteva smette semplicemente di essere. Chi eccelle in questa Via non è colui che crea di più, ma colui che scrive meglio, riducendo al minimo l’errore tra ciò che è stato tracciato e ciò che il mondo è costretto a riconoscere come reale.",
  emissione: "Chi percorre questa Via non rilascia la propria Jigo-ka, la trattiene e la costringe a restare dove non dovrebbe, comprimendola dentro di sé fino a farla diventare peso, pressione, presenza costante. Non è disciplina, è necessità, perché ciò che scorre libero si disperde, si perde, smette di appartenere. L’analista allora accumula, e il corpo lo tradisce: i muscoli si tendono oltre il naturale, il respiro si spezza in scatti irregolari, sotto la pelle iniziano a comparire venature di luce che pulsano come crepe pronte a cedere. La Jigo-ka non resta ferma, si muove, spinge contro i limiti del corpo, deforma leggermente la postura, fa vibrare l’aria attorno, come se la realtà stessa stesse cercando di adattarsi a qualcosa di troppo grande per restare contenuto. Più viene trattenuta, più diventa visibile: bagliori instabili filtrano tra le dita serrate, sottili scosse percorrono il terreno sotto i piedi, gli oggetti vicini tremano appena, come anticipando ciò che sta per accadere. Il corpo diventa un contenitore imperfetto, una soglia sotto pressione, e quando cede non c’è gesto netto né forma controllata: c’è una frattura. L’energia non viene lanciata, esplode attraverso il corpo e lo spazio, si propaga in onde sporche e irregolari, sfondando ciò che incontra, sollevando detriti, piegando superfici, lasciando dietro di sé un campo deformato, segnato da crepe e residui di luce che si disperdono lentamente. Le tecniche non colpiscono, travolgono; non si fermano, continuano oltre, come se nulla fosse abbastanza per contenerle. Ogni utilizzo di questa Via è un equilibrio instabile tra contenimento e collasso, tra volontà e cedimento, e chi eccelle non è colui che sprigiona più potenza, ma colui che riesce a sostenere più a lungo quella pressione, che conosce il momento esatto in cui il corpo inizierà a rompersi e decide comunque di arrivarci.",
  trasformazione: "Chi percorre questa Via non altera ciò che vede, ne nega la stabilità. Ogni cosa esiste in uno stato preciso solo perché continua a mantenerlo, ma basta interrompere quell’equilibrio perché inizi a cedere. L’analista non crea e non controlla: interviene nel punto esatto in cui una forma smette di essere coerente con sé stessa. La Jigo-ka non impone una nuova natura, ma costringe quella esistente a cambiare stato, come se fosse sempre stata instabile e solo ora lo stesse mostrando. Un corpo può diventare rigido come pietra e un istante dopo perdere consistenza, una fiamma può solidificarsi, un suono può acquisire peso, una superficie può cedere senza rompersi davvero. Nulla si trasforma in modo pulito, ogni mutazione è imperfetta, attraversata da tensioni e transizioni visibili, come se più stati cercassero di esistere nello stesso momento. Il mondo, sotto questa influenza, non si modifica: vacilla. E più l’analista insiste, più le cose perdono definizione, oscillando tra ciò che sono e ciò che potrebbero essere. Chi eccelle in questa Via non è colui che cambia di più, ma colui che comprende quanto poco serva perché qualcosa smetta di essere ciò che era.",
  supporto: "Chi percorre questa Via non proietta la propria Jigo-ka all’esterno, la richiude dentro di sé e la costringe a circolare dove normalmente non dovrebbe, trasformando il corpo in un sistema di pressione costante. Ogni nodo diventa una camera, ogni battito un impulso, ogni respiro una spinta che ridistribuisce l’energia nelle fibre, nei tendini, nelle ossa. La forza non viene evocata: viene costruita istante dopo istante, accumulata nei movimenti più piccoli, trattenuta fino a quando il corpo non inizia a reagire, adattandosi, irrigidendosi, rispondendo alla violenza con nuova struttura. La Jigo-ka scorre sotto la pelle come una corrente visibile, seguendo traiettorie precise, addensandosi nei punti che verranno usati, lasciando altre parti vuote, temporaneamente sacrificate. Ogni potenziamento è una riscrittura parziale del corpo, ogni scelta una rinuncia a qualcos’altro, perché nulla può essere sostenuto ovunque nello stesso momento. Il dolore non viene evitato, viene integrato, convertito, reso parte del funzionamento stesso, fino a diventare carburante. Chi eccelle in questa Via non è colui che possiede il corpo più forte, ma colui che lo conosce abbastanza da modificarlo mentre combatte, mantenendo il controllo anche quando ciò che scorre dentro di lui non dovrebbe restare contenuto.",
}
