import type { SocialBlueprintDef, SocialMaterialCost, SocialMaterialId } from './types'

function mat(materialId: SocialMaterialId, quantity: number): SocialMaterialCost {
  return { materialId, quantity }
}

/** Catalogo blueprint Shakai Kaikyū — seed per Fase 6. */
export const SOCIAL_BLUEPRINTS: readonly SocialBlueprintDef[] = [
  // ─── Medico ───
  {
    id: 'medico-bendaggio-semplice',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-minarai',
    kind: 'recipe',
    name: 'Bendaggio semplice',
    description: 'Ripristina 5 HP a chi lo usa.',
    materials: [mat('stoffa', 2)],
  },
  {
    id: 'medico-analgesico-lieve',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-minarai',
    kind: 'recipe',
    name: 'Analgesico lieve',
    description: 'Annulla per 1 turno la penalità narrativa di una ferita lieve.',
    materials: [mat('erba_comune', 1)],
  },
  {
    id: 'medico-sedativo-blando',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-minarai',
    kind: 'recipe',
    name: 'Sedativo blando',
    description: 'Rimuove 1 stack di uno status emotivo a scelta.',
    materials: [mat('erba_comune', 1), mat('reagente', 1)],
  },
  {
    id: 'medico-disinfettante',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-minarai',
    kind: 'recipe',
    name: 'Disinfettante',
    description: 'Impedisce che una ferita lieve peggiori (blocca infezione narrativa).',
    materials: [mat('reagente', 1)],
  },
  {
    id: 'medico-kit-sutura',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-gekai',
    kind: 'recipe',
    name: 'Kit di sutura chirurgica',
    description: 'Ripristina 10 HP; utilizzabile solo dal medico stesso.',
    materials: [mat('stoffa', 2), mat('componente_fine', 1)],
  },
  {
    id: 'medico-trasfusione',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-gekai',
    kind: 'recipe',
    name: 'Trasfusione',
    description: 'Trasferisce fino a 10 HP dal medico (o donatore) al paziente.',
    materials: [mat('componente_fine', 1), mat('reagente', 1)],
  },
  {
    id: 'medico-anestetico',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-gekai',
    kind: 'recipe',
    name: 'Anestetico chirurgico',
    description: 'Il paziente ignora ogni penalità da dolore per un\'intera scena.',
    materials: [mat('reagente', 2)],
  },
  {
    id: 'medico-intervento-maggiore',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-gekai',
    kind: 'procedure',
    name: 'Intervento maggiore',
    description: 'Rimuove una condizione grave. Consuma 15 HP del budget giornaliero.',
    materials: [mat('reagente', 2)],
    dailyBudgetCost: 15,
    isProcedure: true,
  },
  {
    id: 'medico-decotto',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-yakushi',
    kind: 'recipe',
    name: 'Decotto rinvigorente',
    description: 'Ripristina 8 HP; funziona ovunque.',
    materials: [mat('erba_comune', 2)],
  },
  {
    id: 'medico-antidoto',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-yakushi',
    kind: 'recipe',
    name: 'Antidoto universale',
    description: 'Annulla un veleno entro 1 turno dall\'assunzione.',
    materials: [mat('erba_comune', 2), mat('erba_rara', 1)],
  },
  {
    id: 'medico-veleno-paralizzante',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-yakushi',
    kind: 'recipe',
    name: 'Veleno paralizzante',
    description: 'Su arma: il primo bersaglio colpito perde ¼ nel turno successivo.',
    materials: [mat('erba_rara', 1), mat('reagente', 1)],
  },
  {
    id: 'medico-veleno-lento',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-yakushi',
    kind: 'recipe',
    name: 'Veleno lento',
    description: '3 danni a turno per 3 turni; non mitigabile da Itami.',
    materials: [mat('erba_rara', 2)],
  },
  {
    id: 'medico-fumo-torpore',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-yakushi',
    kind: 'recipe',
    name: 'Fumo del torpore',
    description: 'Chi inala subisce −2 all\'Indice per una scena.',
    materials: [mat('erba_comune', 1), mat('erba_rara', 1)],
  },
  {
    id: 'medico-zuppa-focolare',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-itamae',
    kind: 'recipe',
    name: 'Zuppa del focolare',
    description: '5 HP per porzione (max 4 porzioni per gruppo).',
    materials: [mat('carne', 2), mat('erba_comune', 1)],
  },
  {
    id: 'medico-onigiri',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-itamae',
    kind: 'recipe',
    name: 'Onigiri del viandante',
    description: 'Ignora la fatica di marcia per un giorno intero.',
    materials: [mat('carne', 1), mat('erba_comune', 1)],
  },
  {
    id: 'medico-piatto-coraggio',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-itamae',
    kind: 'recipe',
    name: 'Piatto del coraggio',
    description: 'Rimuove 1 stack di Osore/Paura.',
    materials: [mat('carne_pregiata', 1), mat('erba_comune', 1)],
  },
  {
    id: 'medico-banchetto-rituale',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-itamae',
    kind: 'recipe',
    name: 'Banchetto rituale',
    description: '+1 a una Skiru a scelta per commensale, scena successiva.',
    materials: [mat('carne_pregiata', 2), mat('erba_comune', 2)],
  },
  {
    id: 'medico-panacea',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-iryo-no-oni',
    kind: 'recipe',
    name: 'Panacea',
    description: '15 HP + antiveleno + rimuove 1 stack emotivo in un solo uso.',
    materials: [mat('erba_rara', 1), mat('reagente', 2), mat('componente_fine', 1)],
  },
  {
    id: 'medico-rianimazione',
    tag: '#Medico',
    classId: 'ishi',
    requiredSubclassId: 'ishi-iryo-no-oni',
    kind: 'procedure',
    name: 'Rianimazione',
    description: 'Da 0 HP a 5 HP, una volta per scena. Consuma intero budget residuo (min. 20).',
    dailyBudgetCost: 20,
    isProcedure: true,
  },

  // ─── Artigiano ───
  {
    id: 'artigiano-utensile-campo',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-minarai',
    kind: 'project',
    name: 'Utensile da campo',
    description: 'Coltello, acciarino, punteruolo. Integrità 10.',
    materials: [mat('rottame_metallico', 1)],
  },
  {
    id: 'artigiano-rammendo',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-minarai',
    kind: 'project',
    name: 'Rammendo',
    description: 'Ripristina 5 Integrità a capo o oggetto in stoffa/cuoio.',
    materials: [mat('stoffa', 1)],
  },
  {
    id: 'artigiano-contenitore',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-minarai',
    kind: 'project',
    name: 'Contenitore sigillato',
    description: 'Protegge il contenuto da acqua e contaminazione.',
    materials: [mat('rottame_metallico', 1), mat('stoffa', 1)],
  },
  {
    id: 'artigiano-torcia',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-minarai',
    kind: 'project',
    name: 'Torcia a lunga durata',
    description: 'Luce per un\'intera scena notturna.',
    materials: [mat('legno', 1), mat('stoffa', 1)],
  },
  {
    id: 'artigiano-kaen-bin',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-kajishi',
    kind: 'project',
    name: 'Kaen-bin (火炎瓶)',
    description: 'Molotov artigianale. Area 2 m in fiamme per 2 turni.',
    materials: [mat('reagente', 1), mat('stoffa', 1)],
  },
  {
    id: 'artigiano-arma-bianca',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-kajishi',
    kind: 'project',
    name: 'Arma bianca forgiata',
    description: 'Arma da mischia, Integrità 30. Richiede forgia.',
    materials: [mat('rottame_metallico', 3), mat('legno', 1)],
  },
  {
    id: 'artigiano-armatura-leggera',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-kajishi',
    kind: 'project',
    name: 'Armatura leggera',
    description: 'Scudo 4 (Resistenza T1).',
    materials: [mat('rottame_metallico', 2), mat('cuoio', 2)],
  },
  {
    id: 'artigiano-armatura-pesante',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-kajishi',
    kind: 'project',
    name: 'Armatura pesante',
    description: 'Scudo 8 (T2), −1 m al Movimento.',
    materials: [mat('rottame_metallico', 4), mat('cuoio', 1)],
  },
  {
    id: 'artigiano-riforgiatura',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-kajishi',
    kind: 'procedure',
    name: 'Riforgiatura',
    description: 'Ripristina l\'intera Integrità di un\'arma metallica. Consuma 15 pt budget.',
    materials: [mat('rottame_metallico', 1)],
    dailyBudgetCost: 15,
    isProcedure: true,
  },
  {
    id: 'artigiano-trappola-scatto',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-karakurishi',
    kind: 'project',
    name: 'Trappola a scatto',
    description: 'Piazzata: 8 danni al primo che la attiva.',
    materials: [mat('componente_meccanico', 2), mat('rottame_metallico', 1)],
  },
  {
    id: 'artigiano-serratura',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-karakurishi',
    kind: 'project',
    name: 'Serratura complessa / grimaldello',
    description: 'Apre o blinda un passaggio.',
    materials: [mat('componente_meccanico', 1), mat('componente_fine', 1)],
  },
  {
    id: 'artigiano-balestra',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-karakurishi',
    kind: 'project',
    name: 'Balestra a ripetizione',
    description: 'Integrità 20, ricarica ogni 2 colpi.',
    materials: [mat('componente_meccanico', 2), mat('legno', 1), mat('rottame_metallico', 1)],
  },
  {
    id: 'artigiano-allarme',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-karakurishi',
    kind: 'project',
    name: 'Allarme perimetrale',
    description: 'Segnala l\'ingresso di intrusi in un\'area.',
    materials: [mat('componente_meccanico', 1), mat('stoffa', 1)],
  },
  {
    id: 'artigiano-restauro',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-tsukuroibito',
    kind: 'project',
    name: 'Restauro',
    description: 'Riporta in funzione un oggetto del vecchio mondo rotto o degradato.',
    materials: [mat('componente_fine', 1)],
  },
  {
    id: 'artigiano-recupero-archivio',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-tsukuroibito',
    kind: 'project',
    name: 'Recupero d\'archivio',
    description: 'Rende leggibile un documento, mappa o supporto danneggiato.',
    materials: [mat('carta', 1), mat('reagente', 1)],
  },
  {
    id: 'artigiano-replica',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-tsukuroibito',
    kind: 'project',
    name: 'Replica',
    description: 'Copia funzionale di un oggetto semplice esaminato (+ materiali originali).',
    materials: [mat('componente_fine', 1)],
  },
  {
    id: 'artigiano-capolavoro',
    tag: '#Artigiano',
    classId: 'shokunin',
    requiredSubclassId: 'shokunin-hyakushu',
    kind: 'project',
    name: 'Capolavoro',
    description: 'Progetto noto con Integrità +50% e tratto distintivo (Master). Materiali doppi.',
  },

  // ─── Cacciatore ───
  {
    id: 'cacciatore-selvaggina-minuta',
    tag: '#Cacciatore',
    classId: 'ryoshi',
    requiredSubclassId: 'ryoshi-michishirube',
    kind: 'gather',
    name: 'Selvaggina minuta',
    description: 'Lepri, uccelli, pesci di fiume → 1 Carne.',
    gatherUnits: 3,
  },
  {
    id: 'cacciatore-erbe-campo',
    tag: '#Cacciatore',
    classId: 'ryoshi',
    requiredSubclassId: 'ryoshi-michishirube',
    kind: 'gather',
    name: 'Erbe da campo',
    description: '→ 1 Erba comune.',
    gatherUnits: 2,
  },
  {
    id: 'cacciatore-legname',
    tag: '#Cacciatore',
    classId: 'ryoshi',
    requiredSubclassId: 'ryoshi-michishirube',
    kind: 'gather',
    name: 'Legname',
    description: '→ 1 Legno.',
    gatherUnits: 2,
  },
  {
    id: 'cacciatore-acqua-pulita',
    tag: '#Cacciatore',
    classId: 'ryoshi',
    requiredSubclassId: 'ryoshi-michishirube',
    kind: 'gather',
    name: 'Acqua pulita',
    description: 'Scorta idrica gruppo per un giorno.',
    gatherUnits: 1,
  },
  {
    id: 'cacciatore-grossa-selvaggina',
    tag: '#Cacciatore',
    classId: 'ryoshi',
    requiredSubclassId: 'ryoshi-koya',
    kind: 'gather',
    name: 'Grossa selvaggina',
    description: '→ 2 Carni pregiate, 1 Cuoio.',
    gatherUnits: 8,
  },
  {
    id: 'cacciatore-predatore',
    tag: '#Cacciatore',
    classId: 'ryoshi',
    requiredSubclassId: 'ryoshi-koya',
    kind: 'gather',
    name: 'Predatore',
    description: 'Possibile scena. → 1 Carne pregiata, 2 Cuoi, 1 Trofeo.',
    gatherUnits: 12,
  },
  {
    id: 'cacciatore-abbattimento-commissione',
    tag: '#Cacciatore',
    classId: 'ryoshi',
    requiredSubclassId: 'ryoshi-koya',
    kind: 'gather',
    name: 'Abbattimento su commissione',
    description: 'Elimina minaccia animale segnalata + ricompensa narrativa e 1 Trofeo.',
    gatherUnits: 10,
  },
  {
    id: 'cacciatore-erba-rara',
    tag: '#Cacciatore',
    classId: 'ryoshi',
    requiredSubclassId: 'ryoshi-sasurai',
    kind: 'gather',
    name: 'Erba rara',
    description: '→ 1 Erba rara (solo raccolta).',
    gatherUnits: 6,
  },
  {
    id: 'cacciatore-residuo-onirico',
    tag: '#Cacciatore',
    classId: 'ryoshi',
    requiredSubclassId: 'ryoshi-sasurai',
    kind: 'gather',
    name: 'Residuo onirico',
    description: '→ 1 Frammento onirico.',
    gatherUnits: 8,
  },
  {
    id: 'cacciatore-ricognizione',
    tag: '#Cacciatore',
    classId: 'ryoshi',
    requiredSubclassId: 'ryoshi-sasurai',
    kind: 'gather',
    name: 'Ricognizione',
    description: 'Mappa un settore Onimori: il gruppo non può essere sorpreso entro la giornata.',
    gatherUnits: 5,
  },
  {
    id: 'cacciatore-recupero',
    tag: '#Cacciatore',
    classId: 'ryoshi',
    requiredSubclassId: 'ryoshi-sasurai',
    kind: 'gather',
    name: 'Recupero',
    description: 'Riporta oggetto o corpo da zona inaccessibile ad altri.',
    gatherUnits: 10,
  },
  {
    id: 'cacciatore-linea-trappole',
    tag: '#Cacciatore',
    classId: 'ryoshi',
    requiredSubclassId: 'ryoshi-michimori',
    kind: 'gather',
    name: 'Linea di trappole',
    description: '3 catture passive Selvaggina minuta entro 24h.',
    gatherUnits: 6,
    gatherRequires: [mat('componente_meccanico', 1)],
  },
  {
    id: 'cacciatore-sentiero-sicuro',
    tag: '#Cacciatore',
    classId: 'ryoshi',
    requiredSubclassId: 'ryoshi-michimori',
    kind: 'gather',
    name: 'Sentiero sicuro',
    description: 'Percorso tra due punti noti senza pericoli ambientali per un giorno.',
    gatherUnits: 8,
  },
  {
    id: 'cacciatore-nascondiglio',
    tag: '#Cacciatore',
    classId: 'ryoshi',
    requiredSubclassId: 'ryoshi-michimori',
    kind: 'gather',
    name: 'Nascondiglio',
    description: 'Riparo occultato: una notte senza rischio imboscata.',
    gatherUnits: 5,
  },
  {
    id: 'cacciatore-preda-leggendaria',
    tag: '#Cacciatore',
    classId: 'ryoshi',
    requiredSubclassId: 'ryoshi-ryokon',
    kind: 'gather',
    name: 'Preda leggendaria',
    description: 'Intero budget giornaliero, sempre scena. 1 Trofeo maggiore + materiali speciali.',
    gatherUnits: 30,
  },

  // ─── Politico (template Patti) ───
  {
    id: 'politico-patto-peso-1',
    tag: '#Politico',
    classId: 'seijika',
    requiredSubclassId: 'seijika-kojin',
    kind: 'pact_template',
    name: 'Favore spicciolo',
    description: 'Informazione di strada, occhio chiuso, messaggio recapitato.',
    weightOrPower: 1,
  },
  {
    id: 'politico-patto-peso-2',
    tag: '#Politico',
    classId: 'seijika',
    requiredSubclassId: 'seijika-kojin',
    kind: 'pact_template',
    name: 'Debito personale',
    description: 'Alloggio sicuro, testimone, accesso a luogo chiuso.',
    weightOrPower: 2,
  },
  {
    id: 'politico-patto-peso-3',
    tag: '#Politico',
    classId: 'seijika',
    requiredSubclassId: 'seijika-kojin',
    kind: 'pact_template',
    name: 'Impegno di gruppo',
    description: 'Scorta armata, sciopero/raduno (popolare), dossier (sotterranea).',
    weightOrPower: 3,
  },
  {
    id: 'politico-patto-peso-4',
    tag: '#Politico',
    classId: 'seijika',
    requiredSubclassId: 'seijika-kojin',
    kind: 'pact_template',
    name: 'Mobilitazione',
    description: 'Appoggio Ordine (formale), folla (popolare), sparizione prova (sotterranea).',
    weightOrPower: 4,
  },
  {
    id: 'politico-patto-peso-5',
    tag: '#Politico',
    classId: 'seijika',
    requiredSubclassId: 'seijika-kuromaku',
    kind: 'pact_template',
    name: 'Atto che cambia gli equilibri',
    description: 'Alleanza fazioni, amnistia, caduta funzionario. Sempre moderazione.',
    weightOrPower: 5,
    exclusiveSubclassIds: ['seijika-kuromaku'],
  },
  {
    id: 'politico-rinnovo',
    tag: '#Politico',
    classId: 'seijika',
    requiredSubclassId: 'seijika-kuromaku',
    kind: 'pact_template',
    name: 'Rinnovo',
    description: 'Patto speso rinegoziato: torna attivo con Peso −1.',
    exclusiveSubclassIds: ['seijika-kuromaku'],
  },
  {
    id: 'politico-delega',
    tag: '#Politico',
    classId: 'seijika',
    requiredSubclassId: 'seijika-kagenui',
    kind: 'pact_template',
    name: 'Patto delegato',
    description: 'Il beneficio del richiamo può essere girato a un altro giocatore.',
    exclusiveSubclassIds: ['seijika-kagenui', 'seijika-kuromaku'],
  },

  // ─── Sacerdote (riti / Ofuda) ───
  {
    id: 'sacerdote-conforto',
    tag: '#Sacerdote',
    classId: 'shisai',
    requiredSubclassId: 'shisai-minarai-miko',
    kind: 'rite',
    name: 'Ofuda del Conforto',
    description: 'Rimuove 1 stack emotivo al detentore.',
    materials: [mat('carta', 1)],
    weightOrPower: 1,
  },
  {
    id: 'sacerdote-soglia',
    tag: '#Sacerdote',
    classId: 'shisai',
    requiredSubclassId: 'shisai-minarai-miko',
    kind: 'rite',
    name: 'Ofuda della Soglia',
    description: 'Apposto a porta/passaggio: il sacerdote sa se qualcuno lo attraversa.',
    materials: [mat('carta', 1)],
    weightOrPower: 1,
  },
  {
    id: 'sacerdote-veglia',
    tag: '#Sacerdote',
    classId: 'shisai',
    requiredSubclassId: 'shisai-minarai-miko',
    kind: 'rite',
    name: 'Ofuda della Veglia',
    description: 'Chi lo porta non può essere sorpreso nel sonno per una notte.',
    materials: [mat('carta', 1), mat('erba_comune', 1)],
    weightOrPower: 2,
  },
  {
    id: 'sacerdote-piccolo-scudo',
    tag: '#Sacerdote',
    classId: 'shisai',
    requiredSubclassId: 'shisai-minarai-miko',
    kind: 'rite',
    name: 'Ofuda del Piccolo Scudo',
    description: 'Assorbe 8 danni (T2), poi si consuma.',
    materials: [mat('carta', 2)],
    weightOrPower: 2,
  },
  {
    id: 'sacerdote-presagio-minore',
    tag: '#Sacerdote',
    classId: 'shisai',
    requiredSubclassId: 'shisai-minarai-miko',
    kind: 'rite',
    name: 'Ofuda del Presagio minore',
    description: 'Master concede un indizio su un pericolo imminente.',
    materials: [mat('carta', 1), mat('frammento_onirico', 1)],
    weightOrPower: 2,
  },
  {
    id: 'sacerdote-purificazione',
    tag: '#Sacerdote',
    classId: 'shisai',
    requiredSubclassId: 'shisai-jareiba',
    kind: 'rite',
    name: 'Ofuda della Purificazione',
    description: 'Rimuove corruzione onirica minore o dissolve residuo Kyōfu.',
    materials: [mat('carta', 2), mat('frammento_onirico', 1)],
    weightOrPower: 3,
  },
  {
    id: 'sacerdote-sonno-quieto',
    tag: '#Sacerdote',
    classId: 'shisai',
    requiredSubclassId: 'shisai-yumetoki',
    kind: 'rite',
    name: 'Ofuda del Sonno Quieto',
    description: 'Nessuna intrusione onirica fino all\'alba.',
    materials: [mat('carta', 2), mat('erba_rara', 1)],
    weightOrPower: 3,
  },
  {
    id: 'sacerdote-lettura',
    tag: '#Sacerdote',
    classId: 'shisai',
    requiredSubclassId: 'shisai-yumetoki',
    kind: 'rite',
    name: 'Ofuda della Lettura',
    description: 'Interpreta un sogno: verità e avvertimento (Master).',
    materials: [mat('carta', 1), mat('frammento_onirico', 1)],
    weightOrPower: 3,
    exclusiveSubclassIds: ['shisai-yumetoki'],
  },
  {
    id: 'sacerdote-esorcismo',
    tag: '#Sacerdote',
    classId: 'shisai',
    requiredSubclassId: 'shisai-jareiba',
    kind: 'rite',
    name: 'Ofuda dell\'Esorcismo',
    description: 'Scaccia Kyōfu minore o spezza possessione.',
    materials: [mat('carta', 3), mat('frammento_onirico', 2)],
    weightOrPower: 4,
    exclusiveSubclassIds: ['shisai-jareiba', 'shisai-koku-no-koe'],
    pathConstraint: 'Fabbricazione solo in luogo consacrato (Jareiba).',
  },
  {
    id: 'sacerdote-grande-scudo',
    tag: '#Sacerdote',
    classId: 'shisai',
    requiredSubclassId: 'shisai-denshosha',
    kind: 'rite',
    name: 'Ofuda del Grande Scudo',
    description: 'Assorbe 17 danni (T4), poi si consuma.',
    materials: [mat('carta', 3), mat('componente_fine', 1)],
    weightOrPower: 4,
  },
  {
    id: 'sacerdote-sigillo',
    tag: '#Sacerdote',
    classId: 'shisai',
    requiredSubclassId: 'shisai-denshosha',
    kind: 'rite',
    name: 'Ofuda del Sigillo',
    description: 'Sigilla luogo/oggetto/varco (Integrità 12).',
    materials: [mat('carta', 3), mat('frammento_onirico', 1)],
    weightOrPower: 4,
  },
  {
    id: 'sacerdote-vuoto',
    tag: '#Sacerdote',
    classId: 'shisai',
    requiredSubclassId: 'shisai-koku-no-koe',
    kind: 'rite',
    name: 'Ofuda del Vuoto',
    description: 'Rito unico concordato col Master. Sempre moderazione.',
    materials: [mat('carta', 4), mat('frammento_onirico', 3), mat('trofeo_maggiore', 1)],
    weightOrPower: 5,
    exclusiveSubclassIds: ['shisai-koku-no-koe'],
  },
] as const

const blueprintById = new Map(SOCIAL_BLUEPRINTS.map((b) => [b.id, b]))

export function getSocialBlueprint(id: string): SocialBlueprintDef | undefined {
  return blueprintById.get(id)
}

export function getSocialBlueprintsForTag(tag: SocialBlueprintDef['tag']): SocialBlueprintDef[] {
  return SOCIAL_BLUEPRINTS.filter((b) => b.tag === tag)
}

export function getSocialBlueprintsForClass(classId: SocialBlueprintDef['classId']): SocialBlueprintDef[] {
  return SOCIAL_BLUEPRINTS.filter((b) => b.classId === classId)
}
