import type { SocialClassDef, SocialClassId, SocialSubclassDef } from './types'

export const SOCIAL_CLASSES: readonly SocialClassDef[] = [
  {
    id: 'ishi',
    skiruId: 'ishi',
    tag: '#Medico',
    nameItalian: 'Medico',
    nameRomaji: 'Ishi',
    nameJa: '医師',
    toolSummary: 'Curare i giocatori; creare preparati (medicinali, veleni, droghe).',
  },
  {
    id: 'shokunin',
    skiruId: 'shokunin',
    tag: '#Artigiano',
    nameItalian: 'Artigiano',
    nameRomaji: 'Shokunin',
    nameJa: '職人',
    toolSummary: 'Riparare e costruire oggetti ed equipaggiamento; forgiare Costrutti materiali (non magici).',
  },
  {
    id: 'ryoshi',
    skiruId: 'ryoshi',
    tag: '#Cacciatore',
    nameItalian: 'Cacciatore',
    nameRomaji: 'Ryōshi',
    nameJa: '猟師',
    toolSummary: 'Tracciare e cacciare prede; raccogliere risorse; orientarsi in ambienti ostili.',
  },
  {
    id: 'seijika',
    skiruId: 'seijika',
    tag: '#Politico',
    nameItalian: 'Politico',
    nameRomaji: 'Seijika',
    nameJa: '政治家',
    toolSummary: 'Stringere e gestire Patti; richiamare favori (aiuto, informazioni, protezione).',
  },
  {
    id: 'shisai',
    skiruId: 'shisai',
    tag: '#Sacerdote',
    nameItalian: 'Sacerdote',
    nameRomaji: 'Shisai',
    nameJa: '司祭',
    toolSummary: 'Fabbricare Ofuda imbuendoli di un Rito; interpretare sogni, presagi ed energie nascoste.',
  },
] as const

export const SOCIAL_SUBCLASSES: readonly SocialSubclassDef[] = [
  // ─── Ishi — Medico ───
  {
    id: 'ishi-minarai',
    classId: 'ishi',
    role: 'keystone',
    nameRomaji: 'Minarai',
    nameJa: '見習い',
    labelItalian: "L'Apprendista",
    xpCost: 5,
    description:
      'Inizio del percorso da medico. Cura fino a ferite d\'entità lieve (sutura); analgesici lievi, sedativi da banco e rimedi di base.',
    dailyHealHpMax: 15,
  },
  {
    id: 'ishi-gekai',
    classId: 'ishi',
    role: 'path',
    nameRomaji: 'Gekai',
    nameJa: '外科医',
    labelItalian: 'Il Bisturi Silenzioso',
    xpCost: 10,
    description: 'Operazioni difficili, anche trapianti; ampia mole di medicinali differenti.',
    dailyHealHpMax: 30,
  },
  {
    id: 'ishi-yakushi',
    classId: 'ishi',
    role: 'path',
    nameRomaji: 'Yakushi',
    nameJa: '薬師',
    labelItalian: 'Il Guardiano delle Radici',
    xpCost: 10,
    description: 'Metodi rudimentali ma efficaci; preparazione di droghe, medicinali e veleni.',
    dailyHealHpMax: 20,
  },
  {
    id: 'ishi-itamae',
    classId: 'ishi',
    role: 'path',
    nameRomaji: 'Itamae',
    nameJa: '板前',
    labelItalian: 'Il Cuoco dei Rimedi',
    xpCost: 10,
    description: 'Talento nel creare e cucinare piatti con assurdi benefici terapeutici.',
    dailyHealHpMax: 15,
  },
  {
    id: 'ishi-iryo-no-oni',
    classId: 'ishi',
    role: 'capstone',
    nameRomaji: 'Iryō no Oni',
    nameJa: '医療の鬼',
    labelItalian: "L'Ogre della Cura",
    xpCost: 20,
    description: 'Può fare tutto ciò che fanno gli altri sentieri, con qualsiasi metodo.',
    dailyHealHpMax: 30,
    prerequisiteIds: ['ishi-minarai'],
  },

  // ─── Shokunin — Artigiano ───
  {
    id: 'shokunin-minarai',
    classId: 'shokunin',
    role: 'keystone',
    nameRomaji: 'Minarai Shokunin',
    nameJa: '見習い職人',
    labelItalian: "L'Apprendista di Bottega",
    xpCost: 5,
    description: 'Utensili semplici, vestiti, piccoli meccanismi; materiali comuni.',
    dailyIntegrityMax: 15,
  },
  {
    id: 'shokunin-kajishi',
    classId: 'shokunin',
    role: 'path',
    nameRomaji: 'Kajishi',
    nameJa: '鍛冶師',
    labelItalian: 'Il Signore della Forgia',
    xpCost: 10,
    description: 'Armi e armature; metalli pesanti e leghe rare.',
    dailyIntegrityMax: 30,
  },
  {
    id: 'shokunin-karakurishi',
    classId: 'shokunin',
    role: 'path',
    nameRomaji: 'Karakurishi',
    nameJa: '絡繰師',
    labelItalian: 'Il Tessitore di Meccanismi',
    xpCost: 10,
    description: 'Macchinari, trappole e dispositivi meccanici complessi.',
    dailyIntegrityMax: 20,
  },
  {
    id: 'shokunin-tsukuroibito',
    classId: 'shokunin',
    role: 'path',
    nameRomaji: 'Tsukuroibito',
    nameJa: '繕い人',
    labelItalian: 'Il Rammendatore di Cose Perdute',
    xpCost: 10,
    description: 'Recupero di oggetti antichi, rotti o rari; restituisce funzionalità al perduto.',
    dailyIntegrityMax: 15,
  },
  {
    id: 'shokunin-hyakushu',
    classId: 'shokunin',
    role: 'capstone',
    nameRomaji: 'Hyakushu no Meishō',
    nameJa: '百手の名匠',
    labelItalian: 'Il Maestro dalle Cento Mani',
    xpCost: 20,
    description: 'Tutti i metodi artigianali, con qualsiasi approccio.',
    dailyIntegrityMax: 30,
    prerequisiteIds: ['shokunin-minarai'],
  },

  // ─── Ryōshi — Cacciatore ───
  {
    id: 'ryoshi-michishirube',
    classId: 'ryoshi',
    role: 'keystone',
    nameRomaji: 'Michishirube no Karyūdo',
    nameJa: '道標の狩人',
    labelItalian: 'Il Cacciatore dei Primi Passi',
    xpCost: 5,
    description: 'Prede minori; zone conosciute senza rischio.',
    dailyGatherMax: 15,
  },
  {
    id: 'ryoshi-koya',
    classId: 'ryoshi',
    role: 'path',
    nameRomaji: 'Kōya no Ryōshi',
    nameJa: '荒野の猟師',
    labelItalian: 'Il Predone della Landa',
    xpCost: 10,
    description: 'Grossa selvaggina e prede pericolose; agguati e abbattimenti rapidi.',
    dailyGatherMax: 30,
  },
  {
    id: 'ryoshi-sasurai',
    classId: 'ryoshi',
    role: 'path',
    nameRomaji: 'Sasurai no Michishirube',
    nameJa: 'さすらいの道標',
    labelItalian: 'Il Nomade degli Onimori',
    xpCost: 10,
    description: 'Orientamento in territori corrotti e instabili dove altri si perderebbero.',
    dailyGatherMax: 20,
  },
  {
    id: 'ryoshi-michimori',
    classId: 'ryoshi',
    role: 'path',
    nameRomaji: 'Michimori',
    nameJa: '道守',
    labelItalian: 'Il Guardiano dei Sentieri',
    xpCost: 10,
    description: 'Trappole e percorsi sicuri per sé e per gli altri.',
    dailyGatherMax: 15,
  },
  {
    id: 'ryoshi-ryokon',
    classId: 'ryoshi',
    role: 'capstone',
    nameRomaji: 'Ryōkon no Nushi',
    nameJa: '猟魂の主',
    labelItalian: 'Lo Spirito della Caccia',
    xpCost: 20,
    description: 'Tutti i metodi di caccia e raccolta.',
    dailyGatherMax: 30,
    prerequisiteIds: ['ryoshi-michishirube'],
  },

  // ─── Seijika — Politico ───
  {
    id: 'seijika-kojin',
    classId: 'seijika',
    role: 'keystone',
    nameRomaji: 'Kojin',
    nameJa: '口人',
    labelItalian: 'La Prima Parola',
    xpCost: 5,
    description: 'Leve minori: richieste semplici, favori tra singoli individui.',
    pactWeightMax: 2,
    pactActiveMax: 2,
  },
  {
    id: 'seijika-meishi',
    classId: 'seijika',
    role: 'path',
    nameRomaji: 'Meishi',
    nameJa: '盟士',
    labelItalian: "Il Sigillo d'Alleanza",
    xpCost: 10,
    description: 'Trattative ufficiali e alleanze tra Ordini.',
    pactWeightMax: 4,
    pactActiveMax: 4,
    tradeoffs: 'Leva formale — 0 efficacia in contesti informali.',
  },
  {
    id: 'seijika-senseki',
    classId: 'seijika',
    role: 'path',
    nameRomaji: 'Senseki',
    nameJa: '煽石',
    labelItalian: 'La Pietra che Smuove',
    xpCost: 10,
    description: 'Muove folle e dicerie.',
    pactWeightMax: 3,
    pactActiveMax: 3,
    tradeoffs: 'Effetto di ogni Patto ritardato nel tempo, non immediato.',
  },
  {
    id: 'seijika-kagenui',
    classId: 'seijika',
    role: 'path',
    nameRomaji: 'Kagenui',
    nameJa: '影縫',
    labelItalian: "Il Cucitore d'Ombre",
    xpCost: 10,
    description: 'Inganno e persuasione individuale; molte relazioni in parallelo.',
    pactWeightMax: 2,
    pactActiveMax: 5,
    tradeoffs: 'Punta alla quantità di Patti, non al peso del singolo Patto.',
  },
  {
    id: 'seijika-kuromaku',
    classId: 'seijika',
    role: 'capstone',
    nameRomaji: 'Kuromaku',
    nameJa: '黒幕',
    labelItalian: 'Il Burattinaio',
    xpCost: 20,
    description: 'Qualsiasi leva politica a disposizione.',
    pactWeightMax: 4,
    pactActiveMax: 5,
    prerequisiteIds: ['seijika-kojin'],
    tradeoffs:
      'Cambiare registro (formale/popolare/sotterraneo) nella stessa giornata → rischio esposizione; il Patto può saltare o ritorsirsi (Master).',
  },

  // ─── Shisai — Sacerdote ───
  {
    id: 'shisai-minarai-miko',
    classId: 'shisai',
    role: 'keystone',
    nameRomaji: 'Minarai no Miko',
    nameJa: '見習いの巫',
    labelItalian: "L'Apprendista del Santuario",
    xpCost: 5,
    description: 'Riti semplici: piccola protezione, conforto, letture minori.',
    ofudaPowerMax: 2,
    ofudaActiveMax: 2,
  },
  {
    id: 'shisai-jareiba',
    classId: 'shisai',
    role: 'path',
    nameRomaji: 'Jareiba',
    nameJa: '邪霊祓',
    labelItalian: 'Il Cacciatore di Ombre',
    xpCost: 10,
    description: 'Purificazione ed esorcismo contro la corruzione onirica.',
    ofudaPowerMax: 4,
    ofudaActiveMax: 4,
    tradeoffs: 'Fabbricazione Ofuda solo in luogo consacrato (0 altrove).',
  },
  {
    id: 'shisai-yumetoki',
    classId: 'shisai',
    role: 'path',
    nameRomaji: 'Yumetoki',
    nameJa: '夢解き',
    labelItalian: 'Il Lettore di Sogni',
    xpCost: 10,
    description: 'Lettura di sogni, presagi ed energie nascoste con metodi antichi.',
    ofudaPowerMax: 3,
    ofudaActiveMax: 3,
    tradeoffs: 'Funziona ovunque, ma ogni Ofuda richiede il doppio del tempo di preparazione.',
  },
  {
    id: 'shisai-denshosha',
    classId: 'shisai',
    role: 'path',
    nameRomaji: 'Denshōsha',
    nameJa: '伝承者',
    labelItalian: 'Il Custode dei Riti Antichi',
    xpCost: 10,
    description: 'Cerimonie e tradizioni che moltiplicano i talismani pronti all\'uso.',
    ofudaPowerMax: 2,
    ofudaActiveMax: 5,
    tradeoffs: 'Quantità di Ofuda attivi, non potenza del singolo rito.',
  },
  {
    id: 'shisai-koku-no-koe',
    classId: 'shisai',
    role: 'capstone',
    nameRomaji: 'Kokū no Koe',
    nameJa: '虚空の声',
    labelItalian: 'La Voce del Vuoto',
    xpCost: 20,
    description: 'Qualsiasi Rito con qualsiasi metodo.',
    ofudaPowerMax: 4,
    ofudaActiveMax: 5,
    prerequisiteIds: ['shisai-minarai-miko'],
    tradeoffs:
      'Cambiare registro rituale nella stessa giornata → usura spirituale (CS o piccola quota vitalità, da tarare).',
  },
] as const

const classById = new Map(SOCIAL_CLASSES.map((c) => [c.id, c]))
const subclassById = new Map(SOCIAL_SUBCLASSES.map((s) => [s.id, s]))

export function getSocialClassDef(id: SocialClassId): SocialClassDef | undefined {
  return classById.get(id)
}

export function getSocialSubclassDef(id: string): SocialSubclassDef | undefined {
  return subclassById.get(id)
}

export function getSocialSubclassesForClass(classId: SocialClassId): SocialSubclassDef[] {
  return SOCIAL_SUBCLASSES.filter((s) => s.classId === classId)
}

export function getSocialClassTag(classId: SocialClassId): SocialClassDef['tag'] | undefined {
  return getSocialClassDef(classId)?.tag
}
