/**
 * Genzai-dō attive (non di grado) — testi da genzai-waza-pool.
 */
import type { GenzaiCatalogEntry } from "./genzai-catalog-types";

export const GENZAI_ACTIVES: GenzaiCatalogEntry[] = [
  {
    slug: "toki-aura-dichiarata",
    nomeRomaji: "Tōki",
    nomeItaliano: "Aura Dichiarata",
    kanji: "闘気",
    poolName: "Tōki (闘気) — Aura Dichiarata",
    flavor: "L'analista rende visibile ciò che gli circola dentro: l'aura si fa materia, scudo o lancia.",
    meccanica:
      "Attiva · [Energetica] · Tier base 2 · CS 2 · 1/4. Armatura: l'aura diventa un Costrutto Solido avvolgente, fisso fino a morte o grande mutamento psichico; conta come Scudo con Resistenza scala-tier e concede +5% di mitigazione finché regge. Proiettile, in alternativa: l'aura defluisce in un arto e si libera in un Proiettile Energetico (sfera 5×5), gittata 15 m, danno = tier.",
    tier: 2,
    tags: ["Energetica"],
    cs: 2,
    tempoQuarti: 1,
    skiruIr: ["kongen", "seimitsu"],
    effetti: [
      {
        tipo: "MANUALE",
        trigger: "AL_LANCIO",
        testo:
          "Modalità Armatura: Costrutto Solido avvolgente (Scudo, Resistenza scala-tier, +5% mitigazione finché regge; fino a morte o grande mutamento psichico).",
        mostra_a: "MASTER",
      },
      {
        tipo: "DANNO",
        trigger: "AL_LANCIO",
        bersaglio: "LINEA",
        durata: { tipo: "ISTANTANEA" },
        valore: { tipo: "TIER" },
        consistenza: "Energetica",
        area: { forma: "linea", profondita_m: 15 },
        nota_master: "Modalità Proiettile (alternativa): sfera 5×5, gittata 15 m, danno = tier.",
      },
    ],
  },
  {
    slug: "raimei-fu-sigillo-del-fulmine",
    nomeRomaji: "Raimei-Fu",
    nomeItaliano: "Sigillo del Fulmine",
    kanji: "雷鳴符",
    poolName: "Raimei-Fu (雷鳴符) — Sigillo del Fulmine",
    flavor: "Un punto segnato a terra, e il cielo è costretto a rispondere.",
    meccanica:
      "Attiva · [Costrutto][Elementale] · Tier base 3 · CS 3 · 1/4. Scegli un punto entro 12 m: un fulmine cade colpendo entro 3 m dall'impatto (danno = tier, applica status). +2 CS per un secondo punto.",
    tier: 3,
    tags: ["Costrutto", "Elementale"],
    cs: 3,
    tempoQuarti: 1,
    skiruIr: ["kongen", "seimitsu"],
    effetti: [
      {
        tipo: "DANNO",
        trigger: "AL_LANCIO",
        bersaglio: "AREA",
        durata: { tipo: "ISTANTANEA" },
        valore: { tipo: "TIER" },
        consistenza: "Elementale",
        area: { forma: "cerchio", raggio_m: 3 },
        nota_master: "Fulmine su punto entro 12 m; applica status elemento (Honshitsu).",
      },
      {
        tipo: "MOD_COSTO",
        trigger: "PRE_LANCIO",
        bersaglio: "SE_STESSO",
        durata: { tipo: "ISTANTANEA" },
        delta_cs: 2,
        nota_master: "+2 CS opzionale per un secondo punto di impatto.",
      },
    ],
  },
  {
    slug: "yoki-no-iki-soffio-yokai",
    nomeRomaji: "Yōki no Iki",
    nomeItaliano: "Soffio dello Yōkai",
    kanji: "妖気の息",
    poolName: "Yōki no Iki (妖気の息) — Soffio dello Yōkai",
    flavor: "Dal respiro dell'analista esala una nebbia che annebbia i sensi e attende solo una scintilla.",
    meccanica:
      "Attiva · [Emanazione][Gassosa] · Tier base 2 · CS 2 · 1/4. Nube per 4 m attorno a te, permane 2 turni. Dentro, i bersagli subiscono −3 all'Indice delle azioni di Riflessi (Hansha). Infiammabile: a contatto con Fuoco o Fulmine s'incendia e sparisce nel turno.",
    tier: 2,
    tags: ["Emanazione", "Gassosa"],
    cs: 2,
    tempoQuarti: 1,
    skiruIr: ["shodo", "seimitsu"],
    effetti: [
      {
        tipo: "ZONA",
        trigger: "AL_LANCIO",
        bersaglio: "SE_STESSO",
        durata: { tipo: "TURNI", n: 2 },
        forma_zona: "cerchio",
        raggio_zona_m: 4,
        ancoraggio: "SEGUE_ANALISTA",
        effetti_zona: {
          a_inizio_turno: {
            tipo: "BUFF_SKIRU",
            trigger: "INIZIO_TURNO",
            bersaglio: "TUTTI_IN_AREA",
            durata: { tipo: "ISTANTANEA" },
            skiru: "hansha",
            valore: { tipo: "FISSO", n: -3 },
            nota_master: "−3 all'Indice Hansha (Riflessi) per chi è nella nube.",
          },
        },
        immunita: ["SE_STESSO"],
      },
      {
        tipo: "MANUALE",
        trigger: "AL_LANCIO",
        testo: "Nube infiammabile: a contatto con Fuoco o Fulmine si incendia e sparisce nel turno.",
        mostra_a: "MASTER",
      },
    ],
  },
  {
    slug: "onnen-dama-globo-rancore",
    nomeRomaji: "Onnen-dama",
    nomeItaliano: "Globo del Rancore",
    kanji: "怨念玉",
    poolName: "Onnen-dama (怨念玉) — Globo del Rancore",
    flavor: "Una sfera di astio fluttua accanto all'analista, e si avventa su chiunque osi colpirlo.",
    meccanica:
      "Attiva · [Costrutto][Energetico] · Tier base 2 · CS 2 · 1/4 + mantenimento. Generi un globo che ti segue per 4 turni; si lancia automaticamente verso la prima fonte di danno subìta, poi esplode in Emanazione a distanza (area 3 m, danno = tier). Si muove a 6 m a turno; oltre la gittata diventa Proiettile e si schianta dritto, con danno e area maggiorati.",
    tier: 2,
    tags: ["Costrutto", "Energetico"],
    cs: 2,
    tempoQuarti: 1,
    skiruIr: ["kongen", "seimitsu"],
    effetti: [
      {
        tipo: "EVOCA_COSTRUTTO",
        trigger: "AL_LANCIO",
        bersaglio: "SE_STESSO",
        durata: { tipo: "TURNI", n: 4 },
        taglia: "Piccola",
        consistenza: "Energetica",
        comportamento: "SEGUE",
        movimento_m: 6,
        nota_master: "Globo che segue per 4 turni (+ mantenimento CS).",
      },
      {
        tipo: "DIFFERITO",
        trigger: "AL_LANCIO",
        bersaglio: "SE_STESSO",
        durata: { tipo: "TURNI", n: 4 },
        finestra_turni: 4,
        rilasci: {
          impatto: {
            tipo: "DANNO",
            trigger: "QUANDO_SUBISCI_DANNO",
            bersaglio: "AREA",
            durata: { tipo: "ISTANTANEA" },
            valore: { tipo: "TIER" },
            consistenza: "Energetica",
            area: { forma: "cerchio", raggio_m: 3 },
            nota_master:
              "Reazione alla prima fonte di danno subìta: esplosione Emanazione a distanza. Oltre 6 m: Proiettile diretto, danno e area maggiorati.",
          },
        },
      },
    ],
  },
  {
    slug: "hashira-colonne-incise",
    nomeRomaji: "Hashira",
    nomeItaliano: "Colonne Incise",
    kanji: "柱",
    poolName: "Hashira (柱) — Colonne Incise",
    flavor: "Due colonne si scrivono dal suolo, pazienti come pilastri di un tempio.",
    meccanica:
      "Attiva · [Costrutto] · Tier base 2 · CS 2 · 1/4. Due colonne emergono dal terreno (pietra, cemento, detriti...), alte 5 m, larghe 1 m, distanti 1 m fra loro e sulla stessa linea; permangono 3 turni.",
    tier: 2,
    tags: ["Costrutto"],
    cs: 2,
    tempoQuarti: 1,
    skiruIr: ["kongen"],
    effetti: [
      {
        tipo: "EVOCA_COSTRUTTO",
        trigger: "AL_LANCIO",
        bersaglio: "ZONA_TERRENO",
        durata: { tipo: "TURNI", n: 3 },
        taglia: "Grande",
        consistenza: "Solido",
        comportamento: "STATICO",
        n_copie: 2,
        nota_master: "Due colonne (5 m alte, 1 m larghe, 1 m distanza, stessa linea); materiale locale.",
      },
    ],
  },
  {
    slug: "utsushi-copia-conforme",
    nomeRomaji: "Utsushi",
    nomeItaliano: "Copia Conforme",
    kanji: "写し",
    poolName: "Utsushi (写し) — Copia Conforme",
    flavor: "L'analista riscrive la stessa frase due volte: due realtà identiche, una appena più breve.",
    meccanica:
      "Attiva · [Nessuna] · CS 2 · 1/4. Copia un tuo Costrutto (stessa consistenza, taglia, forma e Resistenza; eredita effetti e status attivi). Durata = quella base meno 1 turno. Usabile anche durante una creazione: la copia appare entro 3 m dall'originale.",
    tier: null,
    tags: ["Nessuna"],
    cs: 2,
    tempoQuarti: 1,
    skiruIr: ["kongen", "seimitsu"],
    effetti: [
      {
        tipo: "MANUALE",
        trigger: "AL_LANCIO",
        testo:
          "Copia un tuo Costrutto (stessa consistenza, taglia, forma, Resistenza; eredita effetti/status). Durata base −1 turno. Durante creazione: copia entro 3 m dall'originale.",
        mostra_a: "MASTER",
      },
    ],
  },
  {
    slug: "shogeki-te-palmo-elementale",
    nomeRomaji: "Shōgeki-Te",
    nomeItaliano: "Palmo Elementale",
    kanji: "衝撃手",
    poolName: "Shōgeki-Te (衝撃手) — Palmo Elementale",
    flavor: "La mano si vela di un liquido psichico denso e marchia ciò che tocca.",
    meccanica:
      "Attiva · [Contatto][Elementale] · Tier base 1 · CS 1 · 1/4. Colpisci a contatto: danno = tier, applica lo status dell'elemento affine. Richiede Honshitsu.",
    tier: 1,
    tags: ["Contatto", "Elementale"],
    cs: 1,
    tempoQuarti: 1,
    skiruIr: ["gojin", "seimitsu"],
    effetti: [
      {
        tipo: "DANNO",
        trigger: "AL_LANCIO",
        bersaglio: "BERSAGLIO_SINGOLO",
        durata: { tipo: "ISTANTANEA" },
        valore: { tipo: "TIER" },
        consistenza: "Elementale",
      },
      {
        tipo: "MANUALE",
        trigger: "PRE_LANCIO",
        testo: "Applica lo status dell'elemento affine (Honshitsu). Richiede keystone Honshitsu.",
        mostra_a: "MASTER",
      },
    ],
  },
  {
    slug: "genso-ya-dardo-elementale",
    nomeRomaji: "Genso-Ya",
    nomeItaliano: "Dardo Elementale",
    kanji: "元素矢",
    poolName: "Genso-Ya (元素矢) — Dardo Elementale",
    flavor: "Un dardo del proprio elemento, scritto e scoccato in un sol gesto.",
    meccanica:
      "Attiva · [Proiettile][Elementale] · Tier base 1 · CS 1 · 1/4. Proiettile dell'elemento affine in linea retta, gittata 15 m: danno = tier al primo bersaglio, applica status. Richiede Honshitsu.",
    tier: 1,
    tags: ["Proiettile", "Elementale"],
    cs: 1,
    tempoQuarti: 1,
    skiruIr: ["goju", "seimitsu"],
    effetti: [
      {
        tipo: "DANNO",
        trigger: "AL_LANCIO",
        bersaglio: "LINEA",
        durata: { tipo: "ISTANTANEA" },
        valore: { tipo: "TIER" },
        consistenza: "Elementale",
        area: { forma: "linea", profondita_m: 15 },
      },
      {
        tipo: "MANUALE",
        trigger: "PRE_LANCIO",
        testo: "Applica status elemento affine al primo bersaglio. Richiede Honshitsu.",
        mostra_a: "MASTER",
      },
    ],
  },
  {
    slug: "kessho-mei-memento-mori",
    nomeRomaji: "Kesshō-Mei",
    nomeItaliano: "Memento Mori",
    kanji: "結晶銘",
    poolName: "Kesshō-Mei (結晶銘) — Memento Mori",
    flavor:
      "L'analista solidifica il veleno che già scorre nel nemico, e lo trasforma in una lapide che lo insegue.",
    meccanica:
      "Attiva · [Contatto] → [Costrutto][Elementale] · Tier base 3 · CS 3 · 1/4. Tocchi un vivente con almeno 1 stack di status elementale: rimuovi tutte le stack e generi un Costrutto Elementale di taglia proporzionale (1-2 stack = Piccola, 3-4 = Media, 5+ = Grande). Il costrutto segue il bersaglio a 3 m; distrutto, esplode (danno = tier per taglia) e ridistribuisce le stack sui bersagli in gittata.",
    tier: 3,
    tags: ["Contatto", "Elementale"],
    cs: 3,
    tempoQuarti: 1,
    skiruIr: ["gojin", "kongen"],
    effetti: [
      {
        tipo: "MANUALE",
        trigger: "PRE_LANCIO",
        testo:
          "Bersaglio vivente con ≥1 stack status elementale: rimuovi tutte le stack. Taglia costrutto: 1-2 = Piccola, 3-4 = Media, 5+ = Grande.",
        mostra_a: "MASTER",
      },
      {
        tipo: "EVOCA_COSTRUTTO",
        trigger: "AL_LANCIO",
        bersaglio: "BERSAGLIO_SINGOLO",
        durata: { tipo: "TURNI", n: 3 },
        taglia: "Media",
        consistenza: "Elementale",
        comportamento: "SEGUE",
        movimento_m: 3,
        nota_master: "Lapide elementale che segue il bersaglio. Distrutta: esplode (danno = tier) + ridistribuisce stack.",
      },
    ],
  },
  {
    slug: "jiban-terreno-ostile",
    nomeRomaji: "Jiban",
    nomeItaliano: "Terreno Ostile",
    kanji: "地盤",
    poolName: "Jiban (地盤) — Terreno Ostile",
    flavor: "Il suolo stesso viene riscritto: ciò che era terra diventa l'elemento dell'analista.",
    meccanica:
      "Attiva · [Propagazione][Elementale] · Tier base 2 · CS 2 · 1/4. Ricopri il terreno in un'area di 4 m attorno a un punto entro 8 m col tuo elemento affine: zona Propagazione Elementale per 3 turni. Chi vi sta o la attraversa subisce lo status. L'analista è immune.",
    tier: 2,
    tags: ["Propagazione", "Elementale"],
    cs: 2,
    tempoQuarti: 1,
    skiruIr: ["shodo", "seimitsu"],
    effetti: [
      {
        tipo: "ZONA",
        trigger: "AL_LANCIO",
        bersaglio: "ZONA_TERRENO",
        durata: { tipo: "TURNI", n: 3 },
        forma_zona: "cerchio",
        raggio_zona_m: 4,
        ancoraggio: "FISSA",
        effetti_zona: {
          quando_entra: {
            tipo: "APPLICA_STATUS",
            trigger: "ENTRA_IN_ZONA",
            bersaglio: "BERSAGLIO_SINGOLO",
            durata: { tipo: "ISTANTANEA" },
            status: "metamorfosi",
            stack: 1,
            nota_master: "Status elemento affine (Honshitsu) — Master arbitra quale status.",
          },
        },
        immunita: ["SE_STESSO"],
        nota_master: "Punto entro 8 m; Propagazione Elementale per 3 turni. Analista immune.",
      },
      {
        tipo: "MANUALE",
        trigger: "ENTRA_IN_ZONA",
        testo: "Applica status dell'elemento affine (Honshitsu) a chi sta o attraversa la zona.",
        mostra_a: "MASTER",
      },
    ],
  },
];
