/**
 * Hadō-dō attive 11–20 — guida codifica + testi da hado-waza-pool.
 */
import type { HadoCatalogEntry } from "./hado-catalog-types";

export const HADO_ACTIVES: HadoCatalogEntry[] = [
  {
    slug: "tanraku-corto-circuito",
    nomeRomaji: "Tanraku",
    nomeItaliano: "Corto Circuito",
    kanji: "短絡",
    poolName: "Tanraku (短絡) — Corto Circuito",
    flavor: "L'analista riversa la sua energia in un oggetto fino a renderlo una bomba.",
    meccanica:
      "Attiva · [Energetiche][Contatto] · Tier base 2 · CS 2 · 1/4. Sovraccarichi un Costrutto o oggetto finché diventa instabile; a comando o per forte impatto esplode: danno = tier in 3 m. Se ha il tag Batteria, l'esplosione si allarga di 2 m; se colpisce un altro Batteria, quello esplode a metà raggio.",
    tier: 2,
    tags: ["Energetica", "Contatto"],
    cs: 2,
    tempoQuarti: 1,
    skiruIr: ["konjou", "seimitsu"],
    effetti: [
      {
        tipo: "DIFFERITO",
        trigger: "AL_LANCIO",
        bersaglio: "PROPRIO_COSTRUTTO",
        durata: { tipo: "ISTANTANEA" },
        finestra_turni: 1,
        nota_master: "Sovraccarico su Costrutto/oggetto fino all'esplosione.",
        rilasci: {
          impatto: {
            tipo: "DANNO",
            trigger: "ALL_IMPATTO",
            bersaglio: "AREA",
            durata: { tipo: "ISTANTANEA" },
            valore: { tipo: "TIER" },
            consistenza: "Energetica",
            area: { forma: "cerchio", raggio_m: 3 },
          },
          a_comando: {
            tipo: "DANNO",
            trigger: "A_COMANDO",
            bersaglio: "AREA",
            durata: { tipo: "ISTANTANEA" },
            valore: { tipo: "TIER" },
            consistenza: "Energetica",
            area: { forma: "cerchio", raggio_m: 3 },
          },
        },
      },
      {
        tipo: "MANUALE",
        trigger: "AL_LANCIO",
        testo:
          "Se il bersaglio ha tag Batteria: +2 m raggio esplosione; se colpisce un altro Batteria, quello esplode a metà raggio.",
        mostra_a: "MASTER",
      },
    ],
    implementazioneNote: ["Esplosione condizionata Batteria → Master finché manca tag_batteria."],
  },
  {
    slug: "hosha-raffica-psichica",
    nomeRomaji: "Hōsha",
    nomeItaliano: "Raffica Psichica",
    kanji: "放射",
    poolName: "Hōsha (放射) — Raffica Psichica",
    flavor: "Dai palmi e dalle piante, l'energia erompe in una scarica di colpi.",
    meccanica:
      "Attiva · [Proiettile][Energetico] · Tier base 2 · CS 2 · 1/4. Liberi 2 Proiettili Energetici per 15 m, danno = tier ciascuno.",
    tier: 2,
    tags: ["Proiettile", "Energetico"],
    cs: 2,
    tempoQuarti: 1,
    skiruIr: ["konjou", "goju", "seimitsu"],
    effetti: [
      {
        tipo: "DANNO",
        trigger: "AL_LANCIO",
        bersaglio: "LINEA",
        durata: { tipo: "ISTANTANEA" },
        valore: { tipo: "TIER" },
        consistenza: "Energetica",
        area: { forma: "linea", profondita_m: 15 },
        ripetizioni: 2,
      },
    ],
  },
  {
    slug: "tameru-impeto-trattenuto",
    nomeRomaji: "Tameru",
    nomeItaliano: "Impeto Trattenuto",
    kanji: "溜め",
    poolName: "Tameru (溜め) — Impeto Trattenuto",
    flavor: "Comprime, comprime ancora — e poi cede.",
    meccanica:
      "Attiva · [Emanazione][Energetica] · Tier base 2 · CS 2 · 1/4 + carica. Comprimi la Jigo-Ka fino a 2 turni, rilasciabile in qualsiasi momento, in una forza repulsiva per 5 m. Nello stesso turno interrompe o compromette i movimenti attorno, senza danno; al secondo turno è più forte, danno = tier. Se vieni colpito mentre carichi, l'impeto si rilascia prematuramente e ne sei vittima anche tu.",
    tier: 2,
    tags: ["Emanazione", "Energetica"],
    cs: 2,
    tempoQuarti: 1,
    skiruIr: ["konjou", "shodo"],
    effetti: [
      {
        tipo: "DIFFERITO",
        trigger: "AL_LANCIO",
        bersaglio: "SE_STESSO",
        durata: { tipo: "TURNI", n: 2 },
        finestra_turni: 2,
        nota_master: "Carica fino a 2 turni; rilascio repulsivo 5 m.",
        rilasci: {
          a_comando: {
            tipo: "DANNO",
            trigger: "A_COMANDO",
            bersaglio: "AREA",
            durata: { tipo: "ISTANTANEA" },
            valore: { tipo: "TIER" },
            consistenza: "Energetica",
            area: { forma: "cerchio", raggio_m: 5 },
            nota_master:
              "Forza repulsiva 5 m. Turno 1: interrompe o compromette movimenti attorno, senza danno; turno 2: danno = tier.",
          },
          impatto: {
            tipo: "MANUALE",
            trigger: "QUANDO_SUBISCI_DANNO",
            testo: "Se colpito mentre carichi: rilascio prematuro e ne sei vittima anche tu.",
            mostra_a: "MASTER",
          },
        },
      },
      {
        tipo: "MANUALE",
        trigger: "A_COMANDO",
        testo:
          "Rilascio turno 1: solo repulsione 5 m (interrompe movimenti, nessun danno). Rilascio turno 2+: danno = tier nell'area.",
        mostra_a: "MASTER",
      },
    ],
  },
  {
    slug: "hoden-scarica-impatto",
    nomeRomaji: "Hōden",
    nomeItaliano: "Scarica d'Impatto",
    kanji: "放電",
    poolName: "Hōden (放電) — Scarica d'Impatto",
    flavor: "L'energia accumulata in un arto si scarica al contatto, sfondando tutto.",
    meccanica:
      "Attiva · [Contatto][Energetica] · Tier base 2 · CS 2 · 1/4. Carichi una parte del corpo; all'impatto scarichi un'onda d'urto per 4 m che danneggia (= tier) e compromette la stabilità, sfondando pareti, costrutti, ossa. Se non scarichi entro il turno, quella parte del corpo subisce danno = tier.",
    tier: 2,
    tags: ["Contatto", "Energetica"],
    cs: 2,
    tempoQuarti: 1,
    skiruIr: ["konjou", "gojin"],
    effetti: [
      {
        tipo: "DANNO",
        trigger: "ALL_IMPATTO",
        bersaglio: "AREA",
        durata: { tipo: "ISTANTANEA" },
        valore: { tipo: "TIER" },
        consistenza: "Energetica",
        area: { forma: "cerchio", raggio_m: 4 },
      },
      {
        tipo: "DIFFERITO",
        trigger: "AL_LANCIO",
        bersaglio: "SE_STESSO",
        durata: { tipo: "TURNI", n: 1 },
        finestra_turni: 1,
        nota_master: "Carica un arto; deve scaricare all'impatto entro il turno.",
        rilasci: {
          scadenza: {
            tipo: "DANNO",
            trigger: "A_SCADENZA",
            bersaglio: "SE_STESSO",
            durata: { tipo: "ISTANTANEA" },
            valore: { tipo: "TIER" },
            consistenza: "Energetica",
            nota_master: "Se non scarichi entro il turno, la parte caricata subisce danno = tier.",
          },
        },
      },
      {
        tipo: "MANUALE",
        trigger: "ALL_IMPATTO",
        testo:
          "Compromette la stabilità: sfonda pareti, costrutti, ossa (onda d'urto 4 m, danno = tier).",
        mostra_a: "MASTER",
      },
    ],
  },
  {
    slug: "mugen-no-tsukai-famiglio-onirico",
    nomeRomaji: "Mugen no Tsukai",
    nomeItaliano: "Famiglio Onirico",
    kanji: "夢幻の使い",
    poolName: "Mugen no Tsukai (夢幻の使い) — Famiglio Onirico",
    flavor: "L'analista scinde da sé un frammento vivo della propria energia.",
    meccanica:
      "Attiva · [Costrutto][Energetico] · Tier base 2 · CS 2 · 1/4. Dai vita a un famiglio (animale, taglia media) per 3 turni; durante, non guadagni CS a inizio turno. Percorre 8 m e attacca una volta per turno (danno = tier). Se acquisisce un elemento, lo mantiene fino a fine tecnica.",
    tier: 2,
    tags: ["Costrutto", "Energetico"],
    cs: 2,
    tempoQuarti: 1,
    skiruIr: ["konjou", "kongen"],
    effetti: [
      {
        tipo: "EVOCA_COSTRUTTO",
        trigger: "AL_LANCIO",
        bersaglio: "SE_STESSO",
        durata: { tipo: "TURNI", n: 3 },
        taglia: "Media",
        consistenza: "Energetica",
        danno: { tipo: "TIER" },
        gittata_controllo_m: 8,
        attacchi_per_turno: 1,
        comportamento: "COMANDATO",
      },
      {
        tipo: "MOD_CS",
        trigger: "INIZIO_TURNO",
        bersaglio: "SE_STESSO",
        durata: { tipo: "TURNI", n: 3 },
        operazione: "BLOCCA_RIGEN",
        quantita: { tipo: "FISSO", n: 1 },
        nota_master: "Durante i 3 turni del famiglio, non guadagni CS a inizio turno.",
      },
      {
        tipo: "MANUALE",
        trigger: "AL_LANCIO",
        testo: "Se il famiglio acquisisce un elemento, lo mantiene fino a fine tecnica.",
        mostra_a: "MASTER",
      },
    ],
  },
  {
    slug: "rensa-baku-detonazione-catena",
    nomeRomaji: "Rensa-Baku",
    nomeItaliano: "Detonazione a Catena",
    kanji: "連鎖爆",
    poolName: "Rensa-Baku (連鎖爆) — Detonazione a Catena",
    flavor: "Tutto ciò che porta la sua firma esplode nello stesso istante.",
    meccanica:
      "Attiva · [Emanazione a distanza][Energetica] · Tier base 3 · CS 3 · 1/4. Selezioni fino a 3 tuoi Costrutti con tag Batteria a vista: esplodono simultaneamente, ognuno come Tanraku. Le zone sovrapposte subiscono danni aumentati.",
    tier: 3,
    tags: ["Emanazione a Distanza", "Energetica"],
    cs: 3,
    tempoQuarti: 1,
    skiruIr: ["konjou", "kashin"],
    effetti: [
      {
        tipo: "MANUALE",
        trigger: "AL_LANCIO",
        testo:
          "Seleziona fino a 3 tuoi Costrutti con tag Batteria a vista: esplodono simultaneamente (ognuno come Tanraku, tier 3, raggio 3 m). Zone sovrapposte: danni aumentati.",
        mostra_a: "MASTER",
      },
    ],
    implementazioneNote: ["Dipende da Costrutti Batteria in campo → Master (🔴)."],
  },
  {
    slug: "kasan-carica-detonante",
    nomeRomaji: "Kasan",
    nomeItaliano: "Carica Detonante",
    kanji: "加算",
    poolName: "Kasan (加算) — Carica Detonante",
    flavor: "Un colpo che non ferisce: aggrava.",
    meccanica:
      "Attiva · [Potenziamento][Nulla] · Tier base 2 · CS 2 · 1/4. La prossima waza dà al bersaglio +1 stack di uno status che già possiede, a tua scelta. Se il bersaglio ha almeno 5 stack di uno status, infliggi danno = tier.",
    tier: 2,
    tags: ["Potenziamento", "Nessuna"],
    cs: 2,
    tempoQuarti: 1,
    skiruIr: ["konjou", "seimitsu"],
    effetti: [
      {
        tipo: "MANUALE",
        trigger: "PRE_LANCIO",
        testo:
          "La prossima waza dà al bersaglio +1 stack di uno status che già possiede (a tua scelta).",
        mostra_a: "MASTER",
      },
      {
        tipo: "DANNO",
        trigger: "AL_LANCIO",
        bersaglio: "BERSAGLIO_SINGOLO",
        durata: { tipo: "ISTANTANEA" },
        valore: { tipo: "TIER" },
        consistenza: "Energetica",
        nota_master: "Se il bersaglio ha ≥ 5 stack di uno status (qualsiasi).",
      },
    ],
    implementazioneNote: ["Condizione ≥5 stack → Master se non modellata."],
  },
  {
    slug: "byo-ancora-psionica",
    nomeRomaji: "Byō",
    nomeItaliano: "Ancora Psionica",
    kanji: "鋲",
    poolName: "Byō (鋲) — Ancora Psionica",
    flavor: "Un punto fisso nello spazio a cui i tuoi colpi obbediscono.",
    meccanica:
      "Attiva · [Costrutto][Energetico] · CS 1 · 1/4. Imprimi su una superficie un piccolo Costrutto invisibile. Per 3 turni, le tue waza Proiettile o Raggio possono sceglierlo come bersaglio finale, aggirando gli ostacoli entro i limiti di gittata.",
    tier: null,
    tags: ["Costrutto", "Energetico"],
    cs: 1,
    tempoQuarti: 1,
    skiruIr: ["konjou", "kongen"],
    effetti: [
      {
        tipo: "EVOCA_COSTRUTTO",
        trigger: "AL_LANCIO",
        bersaglio: "ZONA_TERRENO",
        durata: { tipo: "TURNI", n: 3 },
        taglia: "Piccola",
        consistenza: "Energetica",
        comportamento: "STATICO",
        nota_master: "Costrutto invisibile, statico, su superficie.",
      },
      {
        tipo: "MANUALE",
        trigger: "PRE_LANCIO",
        testo:
          "Per 3 turni, le tue waza Proiettile o Raggio possono scegliere l'Ancora come bersaglio finale, aggirando ostacoli entro gittata.",
        mostra_a: "MASTER",
      },
    ],
  },
  {
    slug: "maikomi-innesto-forzato",
    nomeRomaji: "Maikomi",
    nomeItaliano: "Innesto Forzato",
    kanji: "埋め込み",
    poolName: "Maikomi (埋め込み) — Innesto Forzato",
    flavor: "Pianti una carica e scegli tu quando il mondo cede.",
    meccanica:
      "Attiva · [Emanazione a distanza][Energetica] · Tier base 3 · CS 3 · 1/4. Tocchi un bersaglio (vivente, Costrutto o superficie) e vi innesti una carica. Per 3 turni puoi detonarla, una sola volta: danno = tier in 3 m dal punto d'innesto. Se il bersaglio ha il tag Batteria, l'esplosione è +1 tier.",
    tier: 3,
    tags: ["Emanazione a Distanza", "Energetica"],
    cs: 3,
    tempoQuarti: 1,
    skiruIr: ["konjou", "kashin"],
    effetti: [
      {
        tipo: "DIFFERITO",
        trigger: "AL_LANCIO",
        bersaglio: "BERSAGLIO_SINGOLO",
        durata: { tipo: "TURNI", n: 3 },
        finestra_turni: 3,
        nota_master: "Carica innestata; detonabile 1 volta entro 3 turni.",
        rilasci: {
          a_comando: {
            tipo: "DANNO",
            trigger: "A_COMANDO",
            bersaglio: "AREA",
            durata: { tipo: "ISTANTANEA" },
            valore: { tipo: "TIER" },
            consistenza: "Energetica",
            area: { forma: "cerchio", raggio_m: 3 },
          },
        },
      },
      {
        tipo: "MOD_DANNO",
        trigger: "A_COMANDO",
        bersaglio: "BERSAGLIO_SINGOLO",
        durata: { tipo: "ISTANTANEA" },
        valore: { tipo: "TIER_DELTA", n: 1 },
        nota_master: "+1 tier se il bersaglio innestato ha tag Batteria.",
      },
    ],
    implementazioneNote: ["Bonus Batteria → Master finché manca tag_batteria."],
  },
  {
    slug: "kunou-baku-implosione-sofferenza",
    nomeRomaji: "Kunō-Baku",
    nomeItaliano: "Implosione della Sofferenza",
    kanji: "苦悩爆",
    poolName: "Kunō-Baku (苦悩爆) — Implosione della Sofferenza",
    flavor: "Tutto il dolore inflitto, restituito in un solo lampo.",
    meccanica:
      "Attiva · [Emanazione a distanza][Energetica] · Tier base 3 · CS 3 · 1/4. Scegli un bersaglio entro 8 m con almeno 3 stack di status, qualsiasi combinazione: rimuovi tutte le stack e le converti in un'esplosione centrata sul bersaglio, danno = tier per stack rimossa, area 3 m.",
    tier: 3,
    tags: ["Emanazione a Distanza", "Energetica"],
    cs: 3,
    tempoQuarti: 1,
    skiruIr: ["konjou", "kashin"],
    effetti: [
      {
        tipo: "MANUALE",
        trigger: "PRE_LANCIO",
        testo:
          "Bersaglio entro 8 m con ≥ 3 stack di status (qualsiasi combinazione): rimuovi tutte le stack.",
        mostra_a: "MASTER",
      },
      {
        tipo: "DANNO",
        trigger: "AL_LANCIO",
        bersaglio: "AREA",
        durata: { tipo: "ISTANTANEA" },
        valore: { tipo: "TIER_PER_STACK", status: "metamorfosi" },
        consistenza: "Energetica",
        area: { forma: "cerchio", raggio_m: 3 },
        nota_master:
          "Danno = tier × stack rimosse (qualsiasi status). Usa conteggio stack Master se non automatico.",
      },
    ],
    implementazioneNote: ["TIER_PER_STACK su status variabile → Master arbitra conteggio stack."],
  },
];
